if(NOT DEFINED PB_BASELINE)
    message(FATAL_ERROR "PB_BASELINE is required")
endif()
execute_process(COMMAND "${PB_BASELINE}" --baseline RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 120)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Baseline tool failed: ${result} ${error}")
endif()
string(REPLACE "\r" "" output "${output}")
string(STRIP "${output}" output)
string(REPLACE "\n" ";" lines "${output}")
list(LENGTH lines count)
if(NOT count EQUAL 34)
    message(FATAL_ERROR "Expected 32 observations and two independent summaries")
endif()
function(Check json expected)
    string(JSON actual ERROR_VARIABLE error GET "${json}" ${ARGN})
    if(error OR NOT actual STREQUAL expected)
        message(FATAL_ERROR "JSON ${ARGN}: expected ${expected}, actual ${actual}, error ${error}")
    endif()
endfunction()
foreach(candidate RANGE 0 1)
    if(candidate EQUAL 0)
        set(name desktop-levels-2x2)
        set(profile 16983458810237240174)
        set(bits 680400)
        set(tiles 346752)
    else()
        set(name desktop-levels-4x4)
        set(profile 17993931145935450460)
        set(bits 162000)
        set(tiles 86688)
    endif()
    foreach(phase RANGE 0 15)
        math(EXPR index "${candidate} * 17 + ${phase}")
        list(GET lines ${index} row)
        Check("${row}" cpu-observation event)
        Check("${row}" cpu-reference backend)
        Check("${row}" "${profile}" modulation profileId)
        Check("${row}" "${phase}" modulation identity FrameSequence)
        Check("${row}" "${phase}" modulation identity interleavePhase)
        Check("${row}" "None" modulation erasure)
        Check("${row}" "1" modulation scaleX)
        Check("${row}" "1" modulation scaleY)
        Check("${row}" "${tiles}" modulation margin samples)
        Check("${row}" "1" modulation margin min)
        Check("${row}" "ON" evaluation verified)
        Check("${row}" "0" evaluation erroneousCodedBits)
        Check("${row}" "${bits}" evaluation comparedCodedBits)
        Check("${row}" "0" evaluation falseAcceptedCodewords)
    endforeach()
    math(EXPR index "${candidate} * 17 + 16")
    math(EXPR expectedBits "${bits} * 16")
    math(EXPR expectedTiles "${tiles} * 16")
    list(GET lines ${index} row)
    Check("${row}" cpu-summary event)
    Check("${row}" "${name}" candidate)
    Check("${row}" "16" metrics frames)
    Check("${row}" "16" metrics verifiedFrames)
    Check("${row}" "${expectedBits}" metrics comparedCodedBits)
    Check("${row}" "${expectedTiles}" metrics margin samples)
    Check("${row}" "65535" metrics verifiedPhases)
    foreach(metric IN ITEMS PreFecBER PreFecFER PostFecFER)
        Check("${row}" "0" metrics ${metric})
    endforeach()
endforeach()
message(STATUS "DesktopLevels actual offline evaluator: 32 frames, both candidates, all phases, zero BER/FER; JSON independently verified")
