if(NOT DEFINED PB_DECODER OR NOT DEFINED PB_EVIDENCE_ROOT)
    message(FATAL_ERROR "PB_DECODER and PB_EVIDENCE_ROOT are required")
endif()
string(RANDOM LENGTH 16 ALPHABET "0123456789abcdef" suffix)
set(directory "${PB_EVIDENCE_ROOT}/${suffix}")
file(MAKE_DIRECTORY "${directory}")
set(existing "${directory}/existing.jsonl")
set(notCreated "${directory}/invalid-arguments.jsonl")
file(WRITE "${existing}" "prior-evidence-must-remain-byte-identical\n")
file(SHA256 "${existing}" before)
execute_process(COMMAND "${PB_DECODER}" --capture-bootstrap --backend wgc --roi 0 0 1 1 --seconds 1 --telemetry "${existing}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 10)
file(SHA256 "${existing}" after)
if(NOT result EQUAL 1 OR NOT error MATCHES "cannot create new telemetry file" OR NOT before STREQUAL after)
    message(FATAL_ERROR "Create-new telemetry failure was not atomic: ${result} ${output} ${error}")
endif()
execute_process(COMMAND "${PB_DECODER}" --capture-bootstrap --backend dxgi --roi 0 0 1 1 --seconds 0 --telemetry "${notCreated}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 10)
if(NOT result EQUAL 2 OR EXISTS "${notCreated}")
    message(FATAL_ERROR "Invalid arguments created telemetry or started capture: ${result} ${output} ${error}")
endif()
message(STATUS "Actual Decoder rejected overwrite and invalid arguments before capture; evidence=${directory}")
