if(NOT DEFINED PB_PROBE)
    message(FATAL_ERROR "PB_PROBE is required")
endif()
execute_process(COMMAND "${PB_PROBE}" RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 10)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Telemetry probe failed: ${result} ${error}")
endif()
string(REPLACE "\r" "" output "${output}")
string(STRIP "${output}" output)
string(REPLACE "\n" ";" lines "${output}")
list(LENGTH lines lineCount)
if(NOT lineCount EQUAL 13)
    message(FATAL_ERROR "Expected thirteen independent JSONL entries")
endif()
list(GET lines 0 accepted)
list(GET lines 1 erased)
list(GET lines 2 final)
list(GET lines 3 transition)
list(GET lines 4 current)
list(GET lines 5 foreignReadback)
list(GET lines 6 foreignVisual)
list(GET lines 7 resetSameDomain)
list(GET lines 8 inactiveReadback)
list(GET lines 9 inactiveCapture)
function(CheckJson json expected)
    string(JSON actual ERROR_VARIABLE parseError GET "${json}" ${ARGN})
    if(parseError OR NOT actual STREQUAL expected)
        message(FATAL_ERROR "JSON path ${ARGN} expected ${expected}: actual=${actual} error=${parseError}")
    endif()
endfunction()
CheckJson("${accepted}" "18446744073709551615" domain captureEpoch)
CheckJson("${accepted}" "18446744073709551615" observation)
CheckJson("${accepted}" "18446744073709551615" identity SessionTag)
CheckJson("${accepted}" "18446744073709551615" identity FrameSequence)
CheckJson("${accepted}" "1732584193" identity BootstrapCrc)
CheckJson("${accepted}" "DxgiQpcTicks" timestamp domain)
CheckJson("${accepted}" "9223372036854775807" timestamp raw)
CheckJson("${accepted}" "-1920" physicalRoi 0)
CheckJson("${accepted}" "0.5" geometry scaleX)
CheckJson("${accepted}" "2" geometry scaleY)
CheckJson("${accepted}" "0.125" copies 0 sampleMidGrayFraction)
CheckJson("${accepted}" "0.25" copies 1 sampleMidGrayFraction)
CheckJson("${accepted}" "0.25" sampleMidGrayFraction)
string(JSON scaleType TYPE "${accepted}" geometry scaleY)
string(JSON identityType TYPE "${accepted}" identity FrameSequence)
if(NOT scaleType STREQUAL "NUMBER" OR NOT identityType STREQUAL "STRING")
    message(FATAL_ERROR "Telemetry must keep numerical geometry and lossless 64-bit identity types")
endif()
string(JSON copies LENGTH "${accepted}" copies)
if(NOT copies EQUAL 2)
    message(FATAL_ERROR "Telemetry lost independent A/B diagnostics")
endif()
foreach(field IN ITEMS identity)
    string(JSON type TYPE "${erased}" "${field}")
    if(NOT type STREQUAL "NULL")
        message(FATAL_ERROR "Erasure fabricated a Bootstrap identity")
    endif()
endforeach()
foreach(field IN ITEMS originX originY)
    string(JSON type TYPE "${erased}" geometry "${field}")
    if(NOT type STREQUAL "NULL")
        message(FATAL_ERROR "Nonfinite geometry is not JSON null")
    endif()
endforeach()
foreach(copy IN ITEMS 0 1)
    string(JSON type TYPE "${erased}" copies ${copy} sampleMidGrayFraction)
    if(NOT type STREQUAL "NULL")
        message(FATAL_ERROR "Nonfinite core sample diagnostics must be JSON null")
    endif()
endforeach()
string(JSON sampleType TYPE "${erased}" sampleMidGrayFraction)
if(NOT sampleType STREQUAL "NULL")
    message(FATAL_ERROR "Nonfinite aggregate core sample diagnostic must be JSON null")
endif()
CheckJson("${erased}" "NonFinitePixel" visualErasure)
CheckJson("${final}" "ON" DiagnosticCpuReadback)
CheckJson("${final}" "dxgi" backend)
CheckJson("${final}" "WaitingForEnvironment" state)
CheckJson("${final}" "DesktopChanged" rebuildReason)
CheckJson("${final}" "CursorPossiblyComposited" captureErasure)
CheckJson("${final}" "7" staleDiagnosticEvents)
CheckJson("${final}" "OFF" visual temporalStateCurrent)
string(JSON finalVisualDomainType TYPE "${final}" visual domain)
if(NOT finalVisualDomainType STREQUAL "NULL")
    message(FATAL_ERROR "Cleared visual state must expose a null domain")
endif()
CheckJson("${transition}" "2" domain captureEpoch)
CheckJson("${transition}" "2" readback domain captureEpoch)
CheckJson("${transition}" "1" visual domain captureEpoch)
CheckJson("${transition}" "ON" readback active)
CheckJson("${transition}" "ON" readback resetPending)
CheckJson("${transition}" "OFF" visual temporalStateCurrent)
CheckJson("${transition}" "7" visual geometryGeneration)
CheckJson("${transition}" "9" visual calibrationGeneration)
CheckJson("${current}" "2" visual domain captureEpoch)
CheckJson("${current}" "220000000000000000000000000000aa" visual domain sourceId)
CheckJson("${current}" "OFF" readback resetPending)
CheckJson("${current}" "ON" visual temporalStateCurrent)
CheckJson("${current}" "0" visual geometryGeneration)
CheckJson("${current}" "0" visual calibrationGeneration)
CheckJson("${current}" "0" visual trackedSessions)
CheckJson("${current}" "0" visual retainedSequences)
CheckJson("${foreignReadback}" "2" readback domain captureEpoch)
CheckJson("${foreignReadback}" "220000000000000000000000000000ab" readback domain sourceId)
CheckJson("${foreignReadback}" "OFF" visual temporalStateCurrent)
CheckJson("${foreignVisual}" "2" visual domain captureEpoch)
CheckJson("${foreignVisual}" "220000000000000000000000000000ab" visual domain sourceId)
CheckJson("${foreignVisual}" "OFF" visual temporalStateCurrent)
CheckJson("${resetSameDomain}" "ON" readback resetPending)
CheckJson("${resetSameDomain}" "OFF" visual temporalStateCurrent)
CheckJson("${inactiveReadback}" "OFF" readback active)
CheckJson("${inactiveReadback}" "OFF" visual temporalStateCurrent)
CheckJson("${inactiveCapture}" "OFF" domainActive)
CheckJson("${inactiveCapture}" "OFF" visual temporalStateCurrent)
list(GET lines 10 levelsEmpty)
list(GET lines 11 levelsMeasured)
list(GET lines 12 levelsEvent)
foreach(metric IN ITEMS PreFecBER PreFecFER PostFecFER)
    string(JSON type TYPE "${levelsEmpty}" desktopLevels candidates 1 metrics ${metric})
    if(NOT type STREQUAL "NULL")
        message(FATAL_ERROR "Empty DesktopLevels denominator was reported as a number: ${metric}")
    endif()
endforeach()
CheckJson("${levelsMeasured}" "16777216" readback processingReservedBytes)
CheckJson("${levelsMeasured}" "2" desktopLevels candidates 1 metrics frames)
CheckJson("${levelsMeasured}" "324000" desktopLevels candidates 1 metrics comparedCodedBits)
CheckJson("${levelsMeasured}" "40500" desktopLevels candidates 1 metrics erroneousCodedBits)
CheckJson("${levelsMeasured}" "0.125" desktopLevels candidates 1 metrics PreFecBER)
CheckJson("${levelsMeasured}" "0.5" desktopLevels candidates 1 metrics PreFecFER)
CheckJson("${levelsMeasured}" "0.5" desktopLevels candidates 1 metrics PostFecFER)
CheckJson("${levelsMeasured}" "1" desktopLevels candidates 1 metrics verifiedFrames)
CheckJson("${levelsMeasured}" "32769" desktopLevels candidates 1 metrics observedPhases)
CheckJson("${levelsMeasured}" "1" desktopLevels candidates 1 metrics verifiedPhases)
CheckJson("${levelsMeasured}" "4096" desktopLevels candidates 1 metrics margin bins)
CheckJson("${levelsMeasured}" "1" desktopLevels candidates 1 metrics margin P001)
CheckJson("${levelsMeasured}" "uncalibrated-max-log-distance" desktopLevels candidates 1 metrics softMetric)
CheckJson("${levelsMeasured}" "3" desktopLevels candidates 1 geometryErasures)
CheckJson("${levelsMeasured}" "4" desktopLevels candidates 1 pilotErasures)
CheckJson("${levelsMeasured}" "5" desktopLevels candidates 1 duplicates)
CheckJson("${levelsMeasured}" "6" desktopLevels unrecognizedBootstrap)
CheckJson("${levelsEvent}" "desktop-levels-observation" event)
CheckJson("${levelsEvent}" "17993931145935450460" desktopLevels profileId)
CheckJson("${levelsEvent}" "OFF" evaluation verified)
string(JSON type TYPE "${levelsEvent}" desktopLevels phaseResidual)
if(NOT type STREQUAL "NULL")
    message(FATAL_ERROR "Nonfinite DesktopLevels pilot diagnostic was not null")
endif()
message(STATUS "Independent CMake JSON parser verified actual telemetry serializers")
