#include "descriptor_test_helpers.h"

#include "pbprotocol/resume_state.h"

#include <catch2/catch_test_macros.hpp>

#include <algorithm>
#include <array>
#include <cstddef>
#include <cstdint>
#include <limits>
#include <span>
#include <utility>
#include <vector>

namespace {

using pbprotocol::kResumeRecordEnvelopeBytes;
using pbprotocol::LoadedResumeState;
using pbprotocol::LoadResumeState;
using pbprotocol::ParseResumeRecord;
using pbprotocol::ProtocolErrorCode;
using pbprotocol::ReceiverResourcePolicy;
using pbprotocol::SerializeResumeRecord;
using pbprotocol::ValidateResumeStateBudget;

// Typed body sizes (tag byte included), pinned by the golden vectors below.
constexpr std::size_t kCompletedBodySize = 73;
constexpr std::size_t kWirehairHeaderBodySize = 45;
constexpr std::size_t kDirectRepeatHeaderBodySize = 17;

[[nodiscard]] constexpr std::byte Byte(const std::uint8_t value) noexcept
{
    return static_cast<std::byte>(value);
}

void WriteUint32LittleEndian(std::span<std::byte> target, const std::uint32_t value) noexcept
{
    for (std::size_t byteIndex = 0; byteIndex < sizeof(value); byteIndex++)
    {
        target[byteIndex] = Byte(
            static_cast<std::uint8_t>((value >> static_cast<unsigned int>(byteIndex * 8U)) & 0xFFU));
    }
}

void WriteUint64LittleEndian(std::span<std::byte> target, const std::uint64_t value) noexcept
{
    for (std::size_t byteIndex = 0; byteIndex < sizeof(value); byteIndex++)
    {
        target[byteIndex] = Byte(
            static_cast<std::uint8_t>((value >> static_cast<unsigned int>(byteIndex * 8U)) & 0xFFU));
    }
}

// Independent (test-local) body writers that hand-roll the documented layout.
// They exist so corruption and conflict fixtures can be constructed without
// relying on the module serializer; byte correctness is anchored by the
// golden literals further below, which were generated by an external
// reference implementation.
[[nodiscard]] std::vector<std::byte> BuildCompletedBody(
    const std::array<std::byte, 16>& sessionIdBytes,
    const std::uint64_t segmentOrdinal,
    const std::uint64_t rawOffset,
    const std::uint64_t rawSize,
    const std::array<std::byte, 32>& digestBytes)
{
    std::vector<std::byte> body(kCompletedBodySize);
    body[0] = Byte(1);
    for (std::size_t byteIndex = 0; byteIndex < 16U; byteIndex++)
    {
        body[1 + byteIndex] = sessionIdBytes[byteIndex];
    }
    WriteUint64LittleEndian(std::span<std::byte>(body).subspan(17), segmentOrdinal);
    WriteUint64LittleEndian(std::span<std::byte>(body).subspan(25), rawOffset);
    WriteUint64LittleEndian(std::span<std::byte>(body).subspan(33), rawSize);
    for (std::size_t byteIndex = 0; byteIndex < 32U; byteIndex++)
    {
        body[41 + byteIndex] = digestBytes[byteIndex];
    }
    return body;
}

[[nodiscard]] std::vector<std::byte> BuildWirehairBody(
    const std::uint64_t segmentOrdinal,
    const std::array<std::byte, 32>& profileBytes,
    const std::vector<std::pair<std::uint32_t, std::vector<std::byte>>>& entries)
{
    std::vector<std::byte> body(kWirehairHeaderBodySize);
    body[0] = Byte(2);
    WriteUint64LittleEndian(std::span<std::byte>(body).subspan(1), segmentOrdinal);
    for (std::size_t byteIndex = 0; byteIndex < 32U; byteIndex++)
    {
        body[9 + byteIndex] = profileBytes[byteIndex];
    }
    WriteUint32LittleEndian(std::span<std::byte>(body).subspan(41), static_cast<std::uint32_t>(entries.size()));
    for (const auto& [outerBlockId, payload] : entries)
    {
        const std::size_t entryStart = body.size();
        body.resize(entryStart + 8);
        WriteUint32LittleEndian(std::span<std::byte>(body).subspan(entryStart), outerBlockId);
        WriteUint32LittleEndian(
            std::span<std::byte>(body).subspan(entryStart + 4U),
            static_cast<std::uint32_t>(payload.size()));
        body.insert(body.end(), payload.begin(), payload.end());
    }
    return body;
}

[[nodiscard]] std::vector<std::byte> BuildDirectRepeatBody(
    const std::uint64_t segmentOrdinal,
    const std::uint32_t directBlockCount,
    const std::vector<std::tuple<std::uint32_t, std::uint32_t, std::vector<std::byte>>>& entries)
{
    std::vector<std::byte> body(kDirectRepeatHeaderBodySize);
    body[0] = Byte(3);
    WriteUint64LittleEndian(std::span<std::byte>(body).subspan(1), segmentOrdinal);
    WriteUint32LittleEndian(std::span<std::byte>(body).subspan(9), directBlockCount);
    WriteUint32LittleEndian(std::span<std::byte>(body).subspan(13), static_cast<std::uint32_t>(entries.size()));
    for (const auto& [blockOrdinal, realPayloadBytes, paddedPayload] : entries)
    {
        const std::size_t entryStart = body.size();
        body.resize(entryStart + 12);
        WriteUint32LittleEndian(std::span<std::byte>(body).subspan(entryStart), blockOrdinal);
        WriteUint32LittleEndian(
            std::span<std::byte>(body).subspan(entryStart + 4U), realPayloadBytes);
        WriteUint32LittleEndian(
            std::span<std::byte>(body).subspan(entryStart + 8U),
            static_cast<std::uint32_t>(paddedPayload.size()));
        body.insert(body.end(), paddedPayload.begin(), paddedPayload.end());
    }
    return body;
}

[[nodiscard]] std::vector<std::byte> WrapEnvelope(
    const std::span<const std::byte> payload)
{
    std::vector<std::byte> record(kResumeRecordEnvelopeBytes + payload.size());
    REQUIRE(SerializeResumeRecord(payload, std::span<std::byte>(record)));
    return record;
}

[[nodiscard]] ReceiverResourcePolicy MakeTestPolicy(
    const std::uint64_t maxResumeBytes) noexcept
{
    ReceiverResourcePolicy resourcePolicy = pbprotocol::test::MakeResourcePolicy();
    resourcePolicy.maxResumeBytes = maxResumeBytes;
    return resourcePolicy;
}

// Small-budget policy for field boundary matrices.
[[nodiscard]] ReceiverResourcePolicy MakeBoundaryPolicy() noexcept
{
    ReceiverResourcePolicy resourcePolicy =
        pbprotocol::test::MakeResourcePolicy();
    resourcePolicy.maxResumeBytes = 8192;
    resourcePolicy.maxRawSegmentBytes = 100;
    resourcePolicy.maxAcceptedFileBytes = 256;
    resourcePolicy.maxOuterBlockBytes = 32;
    resourcePolicy.maxDirectRepeatBlockCount = 8;
    // Cross-field validator rule: the preallocation cap must not exceed
    // maxAcceptedFileBytes, which this boundary policy shrinks to 256.
    resourcePolicy.maxOutputPreallocationBytesWithoutPrompt = 100ULL;
    return resourcePolicy;
}

[[nodiscard]] std::array<std::byte, 16> MakeSidAscending() noexcept
{
    std::array<std::byte, 16> bytes{};
    for (std::size_t byteIndex = 0; byteIndex < 16U; byteIndex++)
    {
        bytes[byteIndex] = Byte(static_cast<std::uint8_t>(byteIndex));
    }
    return bytes;
}

[[nodiscard]] std::array<std::byte, 32> MakeDigestPattern(const std::uint8_t firstByte) noexcept
{
    std::array<std::byte, 32> bytes{};
    for (std::size_t byteIndex = 0; byteIndex < 32U; byteIndex++)
    {
        bytes[byteIndex] = Byte(static_cast<std::uint8_t>(firstByte + byteIndex));
    }
    return bytes;
}

[[nodiscard]] pbprotocol::ResumeCompletedSegmentRecord MakeCompletedRecord(
    const std::array<std::byte, 16>& sessionIdBytes,
    const std::uint64_t segmentOrdinal,
    const std::uint64_t rawOffset,
    const std::uint64_t rawSize,
    const std::uint8_t digestFirstByte) noexcept
{
    return pbprotocol::ResumeCompletedSegmentRecord{
        pbprotocol::SessionId{sessionIdBytes},
        segmentOrdinal,
        rawOffset,
        rawSize,
        pbprotocol::RawDigest{MakeDigestPattern(digestFirstByte)}};
}

[[nodiscard]] pbprotocol::WirehairV2SerializedProfile MakeCanonicalProfile() noexcept
{
    return pbprotocol::test::MakeWirehairProfile(117, 16);
}

[[nodiscard]] pbprotocol::ResumeActiveWirehairCacheRecord MakeGoldenCacheRecord()
{
    pbprotocol::ResumeActiveWirehairCacheRecord record;
    record.segmentOrdinal = 3;
    record.wirehairProfile = MakeCanonicalProfile();
    pbprotocol::ResumeWirehairCacheEntry firstEntry{};
    firstEntry.outerBlockId = 5;
    firstEntry.payload = {Byte(0x11), Byte(0x22), Byte(0x33), Byte(0x44)};
    record.entries.push_back(std::move(firstEntry));
    pbprotocol::ResumeWirehairCacheEntry secondEntry{};
    secondEntry.outerBlockId = 99;
    secondEntry.payload = {Byte(0xAB), Byte(0xCD)};
    record.entries.push_back(std::move(secondEntry));
    return record;
}

[[nodiscard]] pbprotocol::ResumeActiveDirectRepeatRecord MakeGoldenDirectRepeatRecord()
{
    pbprotocol::ResumeActiveDirectRepeatRecord record;
    record.segmentOrdinal = 8;
    record.directBlockCount = 6;
    pbprotocol::ResumeDirectRepeatEntry entry{};
    entry.blockOrdinal = 5;
    entry.realPayloadBytes = 3;
    entry.paddedPayload = {Byte(0x01), Byte(0x02), Byte(0x03), Byte(0x00)};
    record.entries.push_back(std::move(entry));
    return record;
}

// Deterministic xorshift64 generator for the seeded round-trip matrix.
[[nodiscard]] std::uint64_t NextXorShift(std::uint64_t& state) noexcept
{
    state ^= state << 13U;
    state ^= state >> 7U;
    state ^= state << 17U;
    return state;
}
// ===== GOLDEN LITERALS BEGIN =====
// Golden documents generated by an independent reference implementation
// (hand-rolled layout + standalone CRC32C), not by this module. They pin the
// absolute byte layout: envelope v1, tag byte, field order and endianness.
// D1: 91 bytes
std::array<std::byte, 91> kD1{{
        std::byte{0x50}, std::byte{0x42}, std::byte{0x52}, std::byte{0x53}, std::byte{0x01}, std::byte{0x00}, std::byte{0x49}, std::byte{0x00},
        std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x01}, std::byte{0x00},
        std::byte{0x01}, std::byte{0x02}, std::byte{0x03}, std::byte{0x04}, std::byte{0x05}, std::byte{0x06}, std::byte{0x07}, std::byte{0x08},
        std::byte{0x09}, std::byte{0x0A}, std::byte{0x0B}, std::byte{0x0C}, std::byte{0x0D}, std::byte{0x0E}, std::byte{0x0F}, std::byte{0x07},
        std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00},
        std::byte{0x10}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x39},
        std::byte{0x30}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x10},
        std::byte{0x11}, std::byte{0x12}, std::byte{0x13}, std::byte{0x14}, std::byte{0x15}, std::byte{0x16}, std::byte{0x17}, std::byte{0x18},
        std::byte{0x19}, std::byte{0x1A}, std::byte{0x1B}, std::byte{0x1C}, std::byte{0x1D}, std::byte{0x1E}, std::byte{0x1F}, std::byte{0x20},
        std::byte{0x21}, std::byte{0x22}, std::byte{0x23}, std::byte{0x24}, std::byte{0x25}, std::byte{0x26}, std::byte{0x27}, std::byte{0x28},
        std::byte{0x29}, std::byte{0x2A}, std::byte{0x2B}, std::byte{0x2C}, std::byte{0x2D}, std::byte{0x2E}, std::byte{0x2F}, std::byte{0x59},
        std::byte{0x25}, std::byte{0xC9}, std::byte{0xA1}
}};

// D2: 85 bytes
std::array<std::byte, 85> kD2{{
        std::byte{0x50}, std::byte{0x42}, std::byte{0x52}, std::byte{0x53}, std::byte{0x01}, std::byte{0x00}, std::byte{0x43}, std::byte{0x00},
        std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x02}, std::byte{0x03},
        std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x57},
        std::byte{0x48}, std::byte{0x56}, std::byte{0x32}, std::byte{0x01}, std::byte{0x00}, std::byte{0x20}, std::byte{0x00}, std::byte{0xC9},
        std::byte{0xF9}, std::byte{0xF4}, std::byte{0x47}, std::byte{0xBB}, std::byte{0x5B}, std::byte{0x29}, std::byte{0x4B}, std::byte{0x75},
        std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x10},
        std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x02},
        std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x05}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x04},
        std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x11}, std::byte{0x22}, std::byte{0x33}, std::byte{0x44}, std::byte{0x63},
        std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x02}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0xAB},
        std::byte{0xCD}, std::byte{0x9F}, std::byte{0xBE}, std::byte{0x92}, std::byte{0x52}
}};

// D3: 51 bytes
std::array<std::byte, 51> kD3{{
        std::byte{0x50}, std::byte{0x42}, std::byte{0x52}, std::byte{0x53}, std::byte{0x01}, std::byte{0x00}, std::byte{0x21}, std::byte{0x00},
        std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x03}, std::byte{0x08},
        std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x06},
        std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x01}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x05},
        std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x03}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x04},
        std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x01}, std::byte{0x02}, std::byte{0x03}, std::byte{0x00}, std::byte{0x00},
        std::byte{0x38}, std::byte{0x21}, std::byte{0xDB}
}};

// D4: 318 bytes
std::array<std::byte, 318> kD4{{
        std::byte{0x50}, std::byte{0x42}, std::byte{0x52}, std::byte{0x53}, std::byte{0x01}, std::byte{0x00}, std::byte{0x49}, std::byte{0x00},
        std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x01}, std::byte{0x00},
        std::byte{0x01}, std::byte{0x02}, std::byte{0x03}, std::byte{0x04}, std::byte{0x05}, std::byte{0x06}, std::byte{0x07}, std::byte{0x08},
        std::byte{0x09}, std::byte{0x0A}, std::byte{0x0B}, std::byte{0x0C}, std::byte{0x0D}, std::byte{0x0E}, std::byte{0x0F}, std::byte{0x07},
        std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00},
        std::byte{0x10}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x39},
        std::byte{0x30}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x10},
        std::byte{0x11}, std::byte{0x12}, std::byte{0x13}, std::byte{0x14}, std::byte{0x15}, std::byte{0x16}, std::byte{0x17}, std::byte{0x18},
        std::byte{0x19}, std::byte{0x1A}, std::byte{0x1B}, std::byte{0x1C}, std::byte{0x1D}, std::byte{0x1E}, std::byte{0x1F}, std::byte{0x20},
        std::byte{0x21}, std::byte{0x22}, std::byte{0x23}, std::byte{0x24}, std::byte{0x25}, std::byte{0x26}, std::byte{0x27}, std::byte{0x28},
        std::byte{0x29}, std::byte{0x2A}, std::byte{0x2B}, std::byte{0x2C}, std::byte{0x2D}, std::byte{0x2E}, std::byte{0x2F}, std::byte{0x59},
        std::byte{0x25}, std::byte{0xC9}, std::byte{0xA1}, std::byte{0x50}, std::byte{0x42}, std::byte{0x52}, std::byte{0x53}, std::byte{0x01},
        std::byte{0x00}, std::byte{0x43}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00},
        std::byte{0x00}, std::byte{0x02}, std::byte{0x03}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00},
        std::byte{0x00}, std::byte{0x00}, std::byte{0x57}, std::byte{0x48}, std::byte{0x56}, std::byte{0x32}, std::byte{0x01}, std::byte{0x00},
        std::byte{0x20}, std::byte{0x00}, std::byte{0xC9}, std::byte{0xF9}, std::byte{0xF4}, std::byte{0x47}, std::byte{0xBB}, std::byte{0x5B},
        std::byte{0x29}, std::byte{0x4B}, std::byte{0x75}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00},
        std::byte{0x00}, std::byte{0x00}, std::byte{0x10}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00},
        std::byte{0x00}, std::byte{0x00}, std::byte{0x02}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x05}, std::byte{0x00},
        std::byte{0x00}, std::byte{0x00}, std::byte{0x04}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x11}, std::byte{0x22},
        std::byte{0x33}, std::byte{0x44}, std::byte{0x63}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x02}, std::byte{0x00},
        std::byte{0x00}, std::byte{0x00}, std::byte{0xAB}, std::byte{0xCD}, std::byte{0x9F}, std::byte{0xBE}, std::byte{0x92}, std::byte{0x52},
        std::byte{0x50}, std::byte{0x42}, std::byte{0x52}, std::byte{0x53}, std::byte{0x01}, std::byte{0x00}, std::byte{0x21}, std::byte{0x00},
        std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x03}, std::byte{0x08},
        std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x06},
        std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x01}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x05},
        std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x03}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x04},
        std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x01}, std::byte{0x02}, std::byte{0x03}, std::byte{0x00}, std::byte{0x00},
        std::byte{0x38}, std::byte{0x21}, std::byte{0xDB}, std::byte{0x50}, std::byte{0x42}, std::byte{0x52}, std::byte{0x53}, std::byte{0x01},
        std::byte{0x00}, std::byte{0x49}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00},
        std::byte{0x00}, std::byte{0x01}, std::byte{0xF0}, std::byte{0xF1}, std::byte{0xF2}, std::byte{0xF3}, std::byte{0xF4}, std::byte{0xF5},
        std::byte{0xF6}, std::byte{0xF7}, std::byte{0xF8}, std::byte{0xF9}, std::byte{0xFA}, std::byte{0xFB}, std::byte{0xFC}, std::byte{0xFD},
        std::byte{0xFE}, std::byte{0xFF}, std::byte{0x09}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00},
        std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00},
        std::byte{0x00}, std::byte{0x00}, std::byte{0x07}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00},
        std::byte{0x00}, std::byte{0x00}, std::byte{0x30}, std::byte{0x31}, std::byte{0x32}, std::byte{0x33}, std::byte{0x34}, std::byte{0x35},
        std::byte{0x36}, std::byte{0x37}, std::byte{0x38}, std::byte{0x39}, std::byte{0x3A}, std::byte{0x3B}, std::byte{0x3C}, std::byte{0x3D},
        std::byte{0x3E}, std::byte{0x3F}, std::byte{0x40}, std::byte{0x41}, std::byte{0x42}, std::byte{0x43}, std::byte{0x44}, std::byte{0x45},
        std::byte{0x46}, std::byte{0x47}, std::byte{0x48}, std::byte{0x49}, std::byte{0x4A}, std::byte{0x4B}, std::byte{0x4C}, std::byte{0x4D},
        std::byte{0x4E}, std::byte{0x4F}, std::byte{0xA3}, std::byte{0xDD}, std::byte{0xB1}, std::byte{0xA7}
}};

// D5: 91 bytes
std::array<std::byte, 91> kD5{{
        std::byte{0x50}, std::byte{0x42}, std::byte{0x52}, std::byte{0x53}, std::byte{0x01}, std::byte{0x00}, std::byte{0x49}, std::byte{0x00},
        std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x01}, std::byte{0x00},
        std::byte{0x01}, std::byte{0x02}, std::byte{0x03}, std::byte{0x04}, std::byte{0x05}, std::byte{0x06}, std::byte{0x07}, std::byte{0x08},
        std::byte{0x09}, std::byte{0x0A}, std::byte{0x0B}, std::byte{0x0C}, std::byte{0x0D}, std::byte{0x0E}, std::byte{0x0F}, std::byte{0x00},
        std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00},
        std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x01},
        std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0xFF},
        std::byte{0xFF}, std::byte{0xFF}, std::byte{0xFF}, std::byte{0xFF}, std::byte{0xFF}, std::byte{0xFF}, std::byte{0xFF}, std::byte{0xFF},
        std::byte{0xFF}, std::byte{0xFF}, std::byte{0xFF}, std::byte{0xFF}, std::byte{0xFF}, std::byte{0xFF}, std::byte{0xFF}, std::byte{0xFF},
        std::byte{0xFF}, std::byte{0xFF}, std::byte{0xFF}, std::byte{0xFF}, std::byte{0xFF}, std::byte{0xFF}, std::byte{0xFF}, std::byte{0xFF},
        std::byte{0xFF}, std::byte{0xFF}, std::byte{0xFF}, std::byte{0xFF}, std::byte{0xFF}, std::byte{0xFF}, std::byte{0xFF}, std::byte{0x94},
        std::byte{0xE7}, std::byte{0x0C}, std::byte{0x63}
}};

// ===== GOLDEN LITERALS END =====

TEST_CASE("Typed resume documents match independent golden byte vectors",
          "[pbprotocol][resume-state]")
{
    const ReceiverResourcePolicy resourcePolicy = MakeTestPolicy(4096);

    // Empty input is a legal empty state, not an error.
    const auto emptyResult = LoadResumeState({}, resourcePolicy);
    REQUIRE(emptyResult.HasValue());
    CHECK(emptyResult.Value().completedSegments.empty());
    CHECK(emptyResult.Value().activeWirehairCaches.empty());
    CHECK(emptyResult.Value().activeDirectRepeatRecords.empty());
    CHECK_FALSE(emptyResult.Value().hasTruncatedTail);

    const auto d1Result = LoadResumeState(
        std::span<const std::byte>(kD1), resourcePolicy);
    REQUIRE(d1Result.HasValue());
    CHECK_FALSE(d1Result.Value().hasTruncatedTail);
    CHECK(d1Result.Value().activeWirehairCaches.empty());
    CHECK(d1Result.Value().activeDirectRepeatRecords.empty());
    REQUIRE(d1Result.Value().completedSegments.size() == 1U);
    const pbprotocol::ResumeCompletedSegmentRecord& d1Record =
        d1Result.Value().completedSegments[0];
    CHECK(d1Record.sessionId.bytes == MakeSidAscending());
    CHECK(d1Record.segmentOrdinal == 7ULL);
    CHECK(d1Record.rawOffset == 4096ULL);
    CHECK(d1Record.rawSize == 12345ULL);
    for (std::size_t byteIndex = 0; byteIndex < d1Record.rawDigest.bytes.size(); byteIndex++)
    {
        CHECK(d1Record.rawDigest.bytes[byteIndex]
            == Byte(static_cast<std::uint8_t>(0x10U + byteIndex)));
    }

    const auto d2Result = LoadResumeState(
        std::span<const std::byte>(kD2), resourcePolicy);
    REQUIRE(d2Result.HasValue());
    CHECK_FALSE(d2Result.Value().hasTruncatedTail);
    CHECK(d2Result.Value().completedSegments.empty());
    REQUIRE(d2Result.Value().activeWirehairCaches.size() == 1U);
    const pbprotocol::ResumeActiveWirehairCacheRecord& d2Record =
        d2Result.Value().activeWirehairCaches[0];
    CHECK(d2Record.segmentOrdinal == 3ULL);
    CHECK(d2Record.wirehairProfile.bytes == MakeCanonicalProfile().bytes);
    REQUIRE(d2Record.entries.size() == 2U);
    CHECK(d2Record.entries[0].outerBlockId == 5U);
    CHECK(d2Record.entries[0].payload
        == (std::vector<std::byte>{Byte(0x11), Byte(0x22), Byte(0x33), Byte(0x44)}));
    CHECK(d2Record.entries[1].outerBlockId == 99U);
    CHECK(d2Result.Value().activeWirehairCaches[0]
        == MakeGoldenCacheRecord());

    const auto d3Result = LoadResumeState(
        std::span<const std::byte>(kD3), resourcePolicy);
    REQUIRE(d3Result.HasValue());
    CHECK_FALSE(d3Result.Value().hasTruncatedTail);
    REQUIRE(d3Result.Value().activeDirectRepeatRecords.size() == 1U);
    CHECK(d3Result.Value().activeDirectRepeatRecords[0]
        == MakeGoldenDirectRepeatRecord());

    // Multi-record document: two completed records keep input order.
    const auto d4Result = LoadResumeState(
        std::span<const std::byte>(kD4), resourcePolicy);
    REQUIRE(d4Result.HasValue());
    CHECK_FALSE(d4Result.Value().hasTruncatedTail);
    REQUIRE(d4Result.Value().completedSegments.size() == 2U);
    CHECK(d4Result.Value().completedSegments[0]
        == MakeCompletedRecord(MakeSidAscending(), 7, 4096, 12345, 0x10));
    std::array<std::byte, 16> highSid{};
    for (std::size_t byteIndex = 0; byteIndex < 16U; byteIndex++)
    {
        highSid[byteIndex] = Byte(static_cast<std::uint8_t>(0xF0U + byteIndex));
    }
    CHECK(d4Result.Value().completedSegments[1]
        == MakeCompletedRecord(highSid, 9, 0, 7, 0x30));
    CHECK(d4Result.Value().activeWirehairCaches.size() == 1U);
    CHECK(d4Result.Value().activeDirectRepeatRecords.size() == 1U);

    // Boundary-value completed record (ordinal/offset 0, size 1, digest 0xFF).
    const auto d5Result = LoadResumeState(
        std::span<const std::byte>(kD5), resourcePolicy);
    REQUIRE(d5Result.HasValue());
    REQUIRE(d5Result.Value().completedSegments.size() == 1U);
    CHECK(d5Result.Value().completedSegments[0].segmentOrdinal == 0ULL);
    CHECK(d5Result.Value().completedSegments[0].rawOffset == 0ULL);
    CHECK(d5Result.Value().completedSegments[0].rawSize == 1ULL);
    for (const std::byte digestByte : d5Result.Value().completedSegments[0].rawDigest.bytes)
    {
        CHECK(digestByte == Byte(0xFF));
    }

    // Cross-check the module serializer against the independent oracle: a
    // single-append builder document must equal the golden literal byte-wise.
    const pbprotocol::ResumeCompletedSegmentRecord d1Struct{
        pbprotocol::SessionId{MakeSidAscending()}, 7, 4096, 12345,
        pbprotocol::RawDigest{MakeDigestPattern(0x10)}};
    auto singleBuilderResult = pbprotocol::ResumeStateBuilder::Create(resourcePolicy);
    REQUIRE(singleBuilderResult.HasValue());
    pbprotocol::ResumeStateBuilder singleBuilder = std::move(singleBuilderResult).Value();
    CHECK(singleBuilder.AppendCompletedSegment(d1Struct));
    const std::span<const std::byte> d1Document = singleBuilder.GetDocument();
    CHECK(d1Document.size() == kD1.size());
    CHECK(std::equal(d1Document.begin(), d1Document.end(), kD1.begin()));

    auto multiBuilderResult = pbprotocol::ResumeStateBuilder::Create(resourcePolicy);
    REQUIRE(multiBuilderResult.HasValue());
    pbprotocol::ResumeStateBuilder multiBuilder = std::move(multiBuilderResult).Value();
    CHECK(multiBuilder.AppendCompletedSegment(d1Struct));
    CHECK(multiBuilder.AppendActiveWirehairCache(MakeGoldenCacheRecord()));
    CHECK(multiBuilder.AppendDirectRepeatReceivedBlocks(
        MakeGoldenDirectRepeatRecord()));
    const pbprotocol::ResumeCompletedSegmentRecord d4Second{
        pbprotocol::SessionId{highSid}, 9, 0, 7,
        pbprotocol::RawDigest{MakeDigestPattern(0x30)}};
    CHECK(multiBuilder.AppendCompletedSegment(d4Second));
    const std::span<const std::byte> d4Document = multiBuilder.GetDocument();
    CHECK(d4Document.size() == kD4.size());
    CHECK(std::equal(d4Document.begin(), d4Document.end(), kD4.begin()));
}

TEST_CASE("Seeded random documents round-trip and reserialize canonically",
          "[pbprotocol][resume-state]")
{
    struct GeneratedRecordSet
    {
        std::vector<pbprotocol::ResumeCompletedSegmentRecord> completed;
        std::vector<pbprotocol::ResumeActiveWirehairCacheRecord> caches;
        std::vector<pbprotocol::ResumeActiveDirectRepeatRecord> directRecords;
    };

    // Ordinal ranges are disjoint across categories (100s / 5000s / 9000s)
    // so the strict writer can never reject a cross-category claim.
    const auto generateDocument = [&](
        const ReceiverResourcePolicy& resourcePolicy,
        const std::uint64_t seed) -> GeneratedRecordSet
    {
        std::uint64_t randomState = seed | 1ULL;
        GeneratedRecordSet generated{};

        const std::size_t completedCount = static_cast<std::size_t>(
            1ULL + NextXorShift(randomState) % 2ULL);
        const std::size_t cacheCount = static_cast<std::size_t>(
            1ULL + NextXorShift(randomState) % 2ULL);
        const std::size_t directCount = static_cast<std::size_t>(
            1ULL + NextXorShift(randomState) % 2ULL);

        for (std::size_t recordIndex = 0; recordIndex < completedCount; recordIndex++)
        {
            std::array<std::byte, 16> sidBytes{};
            for (std::size_t byteIndex = 0; byteIndex < 16U; byteIndex++)
            {
                sidBytes[byteIndex] = Byte(static_cast<std::uint8_t>(
                    0x40U + recordIndex * 7U + static_cast<unsigned int>(byteIndex)));
            }
            const std::uint64_t rawOffset = NextXorShift(randomState) % 2000ULL;
            const std::uint64_t rawSize =
                1ULL + NextXorShift(randomState) % 64ULL;
            generated.completed.push_back(MakeCompletedRecord(
                sidBytes, 100ULL + recordIndex, rawOffset, rawSize,
                static_cast<std::uint8_t>(0x20U + recordIndex)));
        }

        for (std::size_t recordIndex = 0; recordIndex < cacheCount; recordIndex++)
        {
            pbprotocol::ResumeActiveWirehairCacheRecord record{};
            record.segmentOrdinal = 5000ULL + recordIndex;
            for (std::size_t byteIndex = 0; byteIndex < record.wirehairProfile.bytes.size(); byteIndex++)
            {
                record.wirehairProfile.bytes[byteIndex] = Byte(static_cast<std::uint8_t>(
                    static_cast<unsigned int>(recordIndex) * 3U + static_cast<unsigned int>(byteIndex)));
            }
            const std::size_t entryCount = static_cast<std::size_t>(
                1ULL + NextXorShift(randomState) % 4ULL);
            for (std::size_t entryIndex = 0; entryIndex < entryCount; entryIndex++)
            {
                pbprotocol::ResumeWirehairCacheEntry entry{};
                entry.outerBlockId = static_cast<std::uint32_t>(
                    (recordIndex + 1U) * 64U + entryIndex * 7U);
                const std::size_t payloadBytes = std::min(
                    static_cast<std::size_t>(resourcePolicy.maxOuterBlockBytes),
                    1ULL + NextXorShift(randomState) % 8ULL);
                for (std::size_t byteIndex = 0; byteIndex < payloadBytes; byteIndex++)
                {
                    entry.payload.push_back(Byte(static_cast<std::uint8_t>(
                        static_cast<unsigned int>(entryIndex) * 11U + static_cast<unsigned int>(byteIndex))));
                }
                record.entries.push_back(std::move(entry));
            }
            generated.caches.push_back(std::move(record));
        }

        for (std::size_t recordIndex = 0; recordIndex < directCount; recordIndex++)
        {
            pbprotocol::ResumeActiveDirectRepeatRecord record{};
            record.segmentOrdinal = 9000ULL + recordIndex;
            record.directBlockCount = static_cast<std::uint32_t>(
                1ULL + NextXorShift(randomState) % 4ULL);
            const std::size_t entryCount = std::min(
                static_cast<std::size_t>(record.directBlockCount),
                static_cast<std::size_t>(1ULL + NextXorShift(randomState) % 2ULL));
            for (std::size_t entryIndex = 0; entryIndex < entryCount; entryIndex++)
            {
                pbprotocol::ResumeDirectRepeatEntry entry{};
                entry.blockOrdinal = static_cast<std::uint32_t>(entryIndex);
                const std::size_t paddedBytes = std::min(
                    static_cast<std::size_t>(resourcePolicy.maxOuterBlockBytes),
                    1ULL + NextXorShift(randomState) % 8ULL);
                // Real payload region leaves one canonical zero-padding byte
                // whenever the block size allows it (no underflow at size 1).
                const std::size_t realPayloadBytes =
                    (paddedBytes >= 2U) ? paddedBytes - 1U : 1U;
                entry.realPayloadBytes = static_cast<std::uint32_t>(realPayloadBytes);
                for (std::size_t byteIndex = 0; byteIndex < paddedBytes; byteIndex++)
                {
                    // Canonical zero padding after the real payload region.
                    entry.paddedPayload.push_back(byteIndex < entry.realPayloadBytes
                        ? Byte(static_cast<std::uint8_t>(
                              static_cast<unsigned int>(entryIndex) * 5U + static_cast<unsigned int>(byteIndex)))
                        : std::byte{0});
                }
                record.entries.push_back(std::move(entry));
            }
            generated.directRecords.push_back(std::move(record));
        }

        return generated;
    };

    const std::vector<ReceiverResourcePolicy> policies{
        MakeTestPolicy(2048),
        pbprotocol::test::MakeResourcePolicy()};

    for (std::size_t policyIndex = 0; policyIndex < policies.size(); policyIndex++)
    {
        const ReceiverResourcePolicy& resourcePolicy = policies[policyIndex];
        REQUIRE(static_cast<bool>(pbprotocol::ValidateReceiverResourcePolicy(resourcePolicy)));

        for (std::size_t documentIndex = 0; documentIndex < 20U; documentIndex++)
        {
            const std::uint64_t seed = 0x5EEDBEEFUL + documentIndex * 7919ULL;
            GeneratedRecordSet generated = generateDocument(resourcePolicy, seed);

            auto builderResult = pbprotocol::ResumeStateBuilder::Create(resourcePolicy);
            REQUIRE(builderResult.HasValue());
            pbprotocol::ResumeStateBuilder builder = std::move(builderResult).Value();
            for (const auto& record : generated.completed)
            {
                CHECK(builder.AppendCompletedSegment(record));
            }
            for (const auto& record : generated.caches)
            {
                CHECK(builder.AppendActiveWirehairCache(record));
            }
            for (const auto& record : generated.directRecords)
            {
                CHECK(builder.AppendDirectRepeatReceivedBlocks(record));
            }
            const std::vector<std::byte> document(
                builder.GetDocument().begin(), builder.GetDocument().end());

            // Round-trip: load must reproduce the generated state exactly.
            const auto loadResult = LoadResumeState(
                std::span<const std::byte>(document), resourcePolicy);
            REQUIRE(loadResult.HasValue());
            CHECK_FALSE(loadResult.Value().hasTruncatedTail);
            LoadedResumeState expected{};
            expected.completedSegments = generated.completed;
            expected.activeWirehairCaches = generated.caches;
            expected.activeDirectRepeatRecords = generated.directRecords;
            CHECK(loadResult.Value() == expected);

            // Canonical reserialization law: rebuilding the document from the
            // loaded state (in stored order) is byte-identical.
            auto rebuiltResult = pbprotocol::ResumeStateBuilder::Create(resourcePolicy);
            REQUIRE(rebuiltResult.HasValue());
            pbprotocol::ResumeStateBuilder rebuilt = std::move(rebuiltResult).Value();
            for (const auto& record : loadResult.Value().completedSegments)
            {
                CHECK(rebuilt.AppendCompletedSegment(record));
            }
            for (const auto& record : loadResult.Value().activeWirehairCaches)
            {
                CHECK(rebuilt.AppendActiveWirehairCache(record));
            }
            for (const auto& record : loadResult.Value().activeDirectRepeatRecords)
            {
                CHECK(rebuilt.AppendDirectRepeatReceivedBlocks(record));
            }
            const std::span<const std::byte> rebuiltDocument = rebuilt.GetDocument();
            CHECK(rebuiltDocument.size() == document.size());
            CHECK(std::equal(
                rebuiltDocument.begin(), rebuiltDocument.end(),
                document.begin()));
        }
    }
}


TEST_CASE("Entry order permutations preserve loaded content", "[pbprotocol][resume-state]")
{
    const ReceiverResourcePolicy resourcePolicy = MakeTestPolicy(4096);

    std::vector<std::pair<std::uint32_t, std::vector<std::byte>>> cacheEntries;
    for (std::size_t entryIndex = 0; entryIndex < 4U; entryIndex++)
    {
        std::vector<std::byte> payloadBytes;
        for (std::size_t byteIndex = 0; byteIndex < 6U; byteIndex++)
        {
            payloadBytes.push_back(Byte(static_cast<std::uint8_t>(
                static_cast<unsigned int>(entryIndex) * 17U + static_cast<unsigned int>(byteIndex))));
        }
        cacheEntries.emplace_back(
            static_cast<std::uint32_t>(entryIndex * 13U + 1U), std::move(payloadBytes));
    }

    const std::vector<std::byte> originalBody = BuildWirehairBody(
        21, MakeCanonicalProfile().bytes, cacheEntries);
    std::vector<std::pair<std::uint32_t, std::vector<std::byte>>> reversedEntries(
        cacheEntries.rbegin(), cacheEntries.rend());
    const std::vector<std::byte> reversedBody = BuildWirehairBody(
        21, MakeCanonicalProfile().bytes, reversedEntries);

    // Same for the DirectRepeat record type.
    std::vector<std::tuple<std::uint32_t, std::uint32_t, std::vector<std::byte>>> directEntries;
    for (std::size_t entryIndex = 0; entryIndex < 4U; entryIndex++)
    {
        // First realPayloadBytes carry the pattern; the rest stay zero padding.
        std::vector<std::byte> paddedBytes(8);
        for (std::size_t byteIndex = 0; byteIndex < 5U; byteIndex++)
        {
            paddedBytes[byteIndex] = Byte(static_cast<std::uint8_t>(
                static_cast<unsigned int>(entryIndex + 1U)));
        }
        directEntries.emplace_back(
            static_cast<std::uint32_t>(entryIndex), 5U, std::move(paddedBytes));
    }
    const std::vector<std::byte> originalDirectBody = BuildDirectRepeatBody(
        77, 8, directEntries);
    std::vector<std::tuple<std::uint32_t, std::uint32_t, std::vector<std::byte>>> reversedDirectEntries(
        directEntries.rbegin(), directEntries.rend());
    const std::vector<std::byte> reversedDirectBody = BuildDirectRepeatBody(
        77, 8, reversedDirectEntries);

    const std::vector<std::byte> cacheDocumentA = WrapEnvelope(originalBody);
    const std::vector<std::byte> cacheDocumentB = WrapEnvelope(reversedBody);
    const auto resultA = LoadResumeState(
        std::span<const std::byte>(cacheDocumentA), resourcePolicy);
    REQUIRE(resultA.HasValue());
    CHECK_FALSE(resultA.Value().hasTruncatedTail);
    const auto resultB = LoadResumeState(
        std::span<const std::byte>(cacheDocumentB), resourcePolicy);
    REQUIRE(resultB.HasValue());
    CHECK_FALSE(resultB.Value().hasTruncatedTail);

    const auto normalizeCacheRecord = [](const LoadedResumeState& state) -> pbprotocol::ResumeActiveWirehairCacheRecord
    {
        REQUIRE(state.activeWirehairCaches.size() == 1U);
        pbprotocol::ResumeActiveWirehairCacheRecord record =
            state.activeWirehairCaches[0];
        std::sort(record.entries.begin(), record.entries.end(),
            [](const pbprotocol::ResumeWirehairCacheEntry& lhs,
               const pbprotocol::ResumeWirehairCacheEntry& rhs) noexcept
            { return lhs.outerBlockId < rhs.outerBlockId; });
        return record;
    };
    CHECK(normalizeCacheRecord(resultA.Value())
        == normalizeCacheRecord(resultB.Value()));

    const std::vector<std::byte> directDocumentA = WrapEnvelope(originalDirectBody);
    const std::vector<std::byte> directDocumentB = WrapEnvelope(reversedDirectBody);
    const auto directResultA = LoadResumeState(
        std::span<const std::byte>(directDocumentA), resourcePolicy);
    REQUIRE(directResultA.HasValue());
    CHECK_FALSE(directResultA.Value().hasTruncatedTail);
    const auto directResultB = LoadResumeState(
        std::span<const std::byte>(directDocumentB), resourcePolicy);
    REQUIRE(directResultB.HasValue());
    CHECK_FALSE(directResultB.Value().hasTruncatedTail);

    const auto normalizeDirectRecord = [](const LoadedResumeState& state) -> pbprotocol::ResumeActiveDirectRepeatRecord
    {
        REQUIRE(state.activeDirectRepeatRecords.size() == 1U);
        pbprotocol::ResumeActiveDirectRepeatRecord record =
            state.activeDirectRepeatRecords[0];
        std::sort(record.entries.begin(), record.entries.end(),
            [](const pbprotocol::ResumeDirectRepeatEntry& lhs,
               const pbprotocol::ResumeDirectRepeatEntry& rhs) noexcept
            { return lhs.blockOrdinal < rhs.blockOrdinal; });
        return record;
    };
    CHECK(normalizeDirectRecord(directResultA.Value())
        == normalizeDirectRecord(directResultB.Value()));
}

TEST_CASE("Exact envelope error codes at pinned document offsets", "[pbprotocol][resume-state]")
{
    const ReceiverResourcePolicy resourcePolicy = MakeTestPolicy(4096);
    const std::vector<std::byte> baseDocument = WrapEnvelope(BuildCompletedBody(
        MakeSidAscending(), 7, 4096, 12345, MakeDigestPattern(0x10)));
    REQUIRE(baseDocument.size() == kD1.size());

    // Bad magic: reported at the document start.
    std::vector<std::byte> mutated = baseDocument;
    mutated[0] = Byte('X');
    const auto badMagicResult = LoadResumeState(
        std::span<const std::byte>(mutated), resourcePolicy);
    CHECK_FALSE(badMagicResult.HasValue());
    CHECK(badMagicResult.Error().code == ProtocolErrorCode::InvalidMagic);
    CHECK(badMagicResult.Error().offset == 0U);

    // Unsupported version byte.
    mutated = baseDocument;
    mutated[4] = Byte(7);
    const auto badVersionResult = LoadResumeState(
        std::span<const std::byte>(mutated), resourcePolicy);
    CHECK(badVersionResult.Error().code == ProtocolErrorCode::InvalidEnumValue);
    CHECK(badVersionResult.Error().offset == 4U);

    // Non-zero reserved byte.
    mutated = baseDocument;
    mutated[5] = Byte(1);
    const auto badReservedResult = LoadResumeState(
        std::span<const std::byte>(mutated), resourcePolicy);
    CHECK(badReservedResult.Error().code == ProtocolErrorCode::NonZeroReservedByte);
    CHECK(badReservedResult.Error().offset == 5U);

    // Any payload byte flip breaks the CRC; the offset is the stored-CRC start.
    const std::size_t storedCrcOffset = baseDocument.size() - 4U;
    mutated = baseDocument;
    mutated[14] ^= Byte(0x80);  // first payload (tag) byte
    const auto badPayloadResult = LoadResumeState(
        std::span<const std::byte>(mutated), resourcePolicy);
    CHECK(badPayloadResult.Error().code == ProtocolErrorCode::CrcMismatch);
    CHECK(badPayloadResult.Error().offset == storedCrcOffset);

    // Flipping the stored CRC itself reports at the same offset.
    mutated = baseDocument;
    mutated[storedCrcOffset] ^= Byte(1);
    const auto badStoredCrcResult = LoadResumeState(
        std::span<const std::byte>(mutated), resourcePolicy);
    CHECK(badStoredCrcResult.Error().code == ProtocolErrorCode::CrcMismatch);
    CHECK(badStoredCrcResult.Error().offset == storedCrcOffset);

    // Declared payloadLength = UINT64_MAX overflows the checked total. The
    // single-record API reports LengthOverflow; the document loader classifies
    // the same region as a torn tail because it cannot hold a complete envelope.
    mutated = baseDocument;
    WriteUint64LittleEndian(
        std::span<std::byte>(mutated).subspan(6),
        std::numeric_limits<std::uint64_t>::max());
    const auto singleRecordOverflow = ParseResumeRecord(
        std::span<const std::byte>(mutated), resourcePolicy);
    CHECK_FALSE(singleRecordOverflow.HasValue());
    CHECK(singleRecordOverflow.Error().code == ProtocolErrorCode::LengthOverflow);
    CHECK(singleRecordOverflow.Error().offset == 0U);

    const auto documentOverflow = LoadResumeState(
        std::span<const std::byte>(mutated), resourcePolicy);
    REQUIRE(documentOverflow.HasValue());
    CHECK(documentOverflow.Value().hasTruncatedTail);
    CHECK(documentOverflow.Value().completedSegments.empty());

    // A fully present envelope with an empty payload has no typed body.
    const std::vector<std::byte> emptyBodyDocument = WrapEnvelope({});
    REQUIRE(emptyBodyDocument.size() == kResumeRecordEnvelopeBytes);
    const auto emptyPayloadResult = LoadResumeState(
        std::span<const std::byte>(emptyBodyDocument), resourcePolicy);
    CHECK_FALSE(emptyPayloadResult.HasValue());
    CHECK(emptyPayloadResult.Error().code == ProtocolErrorCode::InvalidRecordSize);
    CHECK(emptyPayloadResult.Error().offset == 14U);

    // Errors inside a second record are mapped through its start offset.
    const std::vector<std::byte> firstRecord = baseDocument;
    std::vector<std::byte> twoRecordDocument = firstRecord;
    const std::size_t secondStart = twoRecordDocument.size();
    twoRecordDocument.insert(
        twoRecordDocument.end(),
        firstRecord.begin(),
        firstRecord.end());
    CHECK(twoRecordDocument.size() == 2U * firstRecord.size());

    twoRecordDocument[secondStart + 0] = Byte('Q');  // bad magic in record 2
    const auto secondMagicResult = LoadResumeState(
        std::span<const std::byte>(twoRecordDocument), resourcePolicy);
    CHECK(secondMagicResult.Error().code == ProtocolErrorCode::InvalidMagic);
    CHECK(secondMagicResult.Error().offset == secondStart);

    twoRecordDocument[secondStart] = Byte('P');  // restore the magic
    twoRecordDocument[secondStart + firstRecord.size() - 4U] ^= Byte(1);
    const auto secondCrcResult = LoadResumeState(
        std::span<const std::byte>(twoRecordDocument), resourcePolicy);
    CHECK(secondCrcResult.Error().code == ProtocolErrorCode::CrcMismatch);
    CHECK(secondCrcResult.Error().offset
        == secondStart + firstRecord.size() - 4U);
}

TEST_CASE("Unknown record type tags fail closed at the body tag offset", "[pbprotocol][resume-state]")
{
    const ReceiverResourcePolicy resourcePolicy = MakeTestPolicy(4096);
    const std::vector<std::byte> completedBody = BuildCompletedBody(
        MakeSidAscending(), 7, 4096, 12345, MakeDigestPattern(0x10));

    const std::array<std::uint32_t, 3> unknownTags{0U, 4U, 255U};
    for (const auto tagValue : unknownTags)
    {
        const std::uint8_t tagByte = static_cast<std::uint8_t>(tagValue);
        std::vector<std::byte> body = completedBody;
        REQUIRE(body.size() == kCompletedBodySize);
        body[0] = Byte(tagByte);
        const std::vector<std::byte> document = WrapEnvelope(
            std::span<const std::byte>(body));
        const auto loadResult = LoadResumeState(
            std::span<const std::byte>(document), resourcePolicy);
        CHECK_FALSE(loadResult.HasValue());
        CHECK(loadResult.Error().code == ProtocolErrorCode::InvalidEnumValue);
        CHECK(loadResult.Error().offset == 14U);
    }

    // A short body carrying the wirehair tag fails deterministically while
    // reading the fixed 32-byte profile: tag+ordinal fit (1+8 bytes), then
    // only 7 of the required 32 profile bytes remain at body offset 9.
    std::vector<std::byte> crossTaggedBody = completedBody;
    crossTaggedBody[0] = Byte(2);  // ActiveWirehairCache tag
    crossTaggedBody.resize(1 + 8U + 7U);
    const std::vector<std::byte> crossTaggedDocument = WrapEnvelope(
        std::span<const std::byte>(crossTaggedBody));
    const auto crossTaggedResult = LoadResumeState(
        std::span<const std::byte>(crossTaggedDocument), resourcePolicy);
    CHECK_FALSE(crossTaggedResult.HasValue());
    CHECK(crossTaggedResult.Error().code == ProtocolErrorCode::TruncatedInput);
    CHECK(crossTaggedResult.Error().offset == 14U + 9U);
}

TEST_CASE("Body structure errors map into document coordinates", "[pbprotocol][resume-state]")
{
    const ReceiverResourcePolicy resourcePolicy = MakeTestPolicy(4096);
    const ReceiverResourcePolicy boundaryPolicy = MakeBoundaryPolicy();

    // Completed body truncated mid-field (valid tag; the ordinal field starts
    // at body offset 17 and only partially exists here).
    {
        std::vector<std::byte> shortBody = BuildCompletedBody(
            MakeSidAscending(), 0, 0, 1, MakeDigestPattern(0x20));
        shortBody.resize(20);
        const auto result = LoadResumeState(
            std::span<const std::byte>(WrapEnvelope(std::span<const std::byte>(shortBody))),
            resourcePolicy);
        CHECK_FALSE(result.HasValue());
        CHECK(result.Error().code == ProtocolErrorCode::TruncatedInput);
        CHECK(result.Error().offset == 14U + 17U);
    }

    // Completed body with one trailing byte.
    {
        std::vector<std::byte> longBody = BuildCompletedBody(
            MakeSidAscending(), 0, 0, 1, MakeDigestPattern(0x20));
        longBody.push_back(Byte(0x7F));
        const auto result = LoadResumeState(
            std::span<const std::byte>(WrapEnvelope(std::span<const std::byte>(longBody))),
            resourcePolicy);
        CHECK_FALSE(result.HasValue());
        CHECK(result.Error().code == ProtocolErrorCode::TrailingBytes);
        CHECK(result.Error().offset == 14U + kCompletedBodySize);
    }

    // Wirehair entryCount declares more entries than the body can hold.
    {
        std::vector<std::byte> body = BuildWirehairBody(
            3, MakeCanonicalProfile().bytes,
            {{7U, std::vector<std::byte>{Byte(0x11), Byte(0x22)}}});
        WriteUint32LittleEndian(std::span<std::byte>(body).subspan(41), 5U);
        const auto result = LoadResumeState(
            std::span<const std::byte>(WrapEnvelope(std::span<const std::byte>(body))),
            resourcePolicy);
        CHECK_FALSE(result.HasValue());
        CHECK(result.Error().code == ProtocolErrorCode::TruncatedInput);
        CHECK(result.Error().offset == 14U + 41U);
    }

    // Wirehair entry with a zero payload length.
    {
        std::vector<std::byte> body = BuildWirehairBody(
            3, MakeCanonicalProfile().bytes, {{7U, {}}});
        const auto result = LoadResumeState(
            std::span<const std::byte>(WrapEnvelope(std::span<const std::byte>(body))),
            boundaryPolicy);
        CHECK_FALSE(result.HasValue());
        CHECK(result.Error().code == ProtocolErrorCode::InvalidRecordSize);
        CHECK(result.Error().offset == 14U + kWirehairHeaderBodySize + 4U);
    }

    // Wirehair entry payload above the policy bound.
    {
        std::vector<std::byte> oversizedPayload(33, Byte(0x5A));
        std::vector<std::byte> body = BuildWirehairBody(
            3, MakeCanonicalProfile().bytes, {{7U, oversizedPayload}});
        const auto result = LoadResumeState(
            std::span<const std::byte>(WrapEnvelope(std::span<const std::byte>(body))),
            boundaryPolicy);
        CHECK_FALSE(result.HasValue());
        CHECK(result.Error().code == ProtocolErrorCode::ResourceLimitExceeded);
        CHECK(result.Error().offset == 14U + kWirehairHeaderBodySize + 4U);
    }
}

// Independent in-test boundary oracle: record ends inside kD4. Kept at
// namespace scope so the constant can participate in static_assert under
// C++20 /permissive- (block-scope automatic objects are rejected there).
constexpr std::array<std::size_t, 5> kD4RecordEnds{0U, 91U, 176U, 227U, 318U};
static_assert(kD4RecordEnds[4] == kD4.size(), "record end drift");

TEST_CASE("Torn tail sweep pins the boundary model at every length", "[pbprotocol][resume-state]")
{
    const ReceiverResourcePolicy resourcePolicy = MakeTestPolicy(4096);
    static_assert(kD4.size() == 318, "golden D4 layout drift");

    const pbprotocol::ResumeCompletedSegmentRecord completedFirst =
        MakeCompletedRecord(MakeSidAscending(), 7, 4096, 12345, 0x10);
    std::array<std::byte, 16> highSid{};
    for (std::size_t byteIndex = 0; byteIndex < 16U; byteIndex++)
    {
        highSid[byteIndex] = Byte(static_cast<std::uint8_t>(0xF0U + byteIndex));
    }
    const pbprotocol::ResumeCompletedSegmentRecord completedSecond =
        MakeCompletedRecord(highSid, 9, 0, 7, 0x30);
    const pbprotocol::ResumeActiveWirehairCacheRecord cacheRecord =
        MakeGoldenCacheRecord();
    const pbprotocol::ResumeActiveDirectRepeatRecord directRecord =
        MakeGoldenDirectRepeatRecord();

    for (std::size_t inputLength = 0; inputLength <= kD4.size() + 2U; inputLength++)
    {
        std::vector<std::byte> input(kD4.begin(), kD4.end());
        if (inputLength < input.size())
        {
            input.resize(inputLength);
        }
        else
        {
            for (std::size_t extraIndex = 0; extraIndex + input.size() < inputLength; extraIndex++)
            {
                input.push_back(Byte(0x5A));
            }
        }

        std::size_t completeRecords = 0;
        bool atBoundary = inputLength == 0U;
        for (std::size_t endIndex = 1U; endIndex < kD4RecordEnds.size(); endIndex++)
        {
            const std::size_t recordEnd = kD4RecordEnds[endIndex];
            if (recordEnd <= inputLength)
            {
                completeRecords++;
                atBoundary = atBoundary || recordEnd == inputLength;
            }
        }

        const auto loadResult = LoadResumeState(
            std::span<const std::byte>(input), resourcePolicy);
        REQUIRE(loadResult.HasValue());
        INFO("torn tail sweep length=" + std::to_string(inputLength));
        CHECK(loadResult.Value().hasTruncatedTail == !atBoundary);

        // The loaded state must equal the first completeRecords records plus
        // the torn-tail flag derived from the independent boundary model.
        LoadedResumeState expected{};
        expected.hasTruncatedTail = !atBoundary;
        for (std::size_t recordIndex = 0; recordIndex < completeRecords; recordIndex++)
        {
            if (recordIndex == 0U || recordIndex == 3U)
            {
                expected.completedSegments.push_back(
                    recordIndex == 0U ? completedFirst : completedSecond);
            }
            else if (recordIndex == 1U)
            {
                expected.activeWirehairCaches.push_back(cacheRecord);
            }
            else
            {
                expected.activeDirectRepeatRecords.push_back(directRecord);
            }
        }
        INFO("torn tail sweep content length=" + std::to_string(inputLength));
        CHECK(loadResult.Value() == expected);
    }
}
TEST_CASE("Conflicts fail closed and identical duplicates dedupe", "[pbprotocol][resume-state]")
{
    const ReceiverResourcePolicy resourcePolicy = MakeTestPolicy(4096);

    // Same completed key with different digests: whole-document conflict at
    // the second record's start.
    {
        const std::vector<std::byte> firstRecord = WrapEnvelope(BuildCompletedBody(
            MakeSidAscending(), 5, 0, 4, MakeDigestPattern(0x11)));
        const std::vector<std::byte> conflictingRecord = WrapEnvelope(BuildCompletedBody(
            MakeSidAscending(), 5, 0, 4, MakeDigestPattern(0x22)));
        std::vector<std::byte> document = firstRecord;
        const std::size_t secondStart = document.size();
        document.insert(document.end(), conflictingRecord.begin(), conflictingRecord.end());
        const auto result = LoadResumeState(
            std::span<const std::byte>(document), resourcePolicy);
        CHECK_FALSE(result.HasValue());
        CHECK(result.Error().code == ProtocolErrorCode::ResumeRecordConflict);
        CHECK(result.Error().offset == secondStart);
    }

    // Byte-identical completed duplicate: deduplicated, no conflict.
    {
        const std::vector<std::byte> firstRecord = WrapEnvelope(BuildCompletedBody(
            MakeSidAscending(), 5, 0, 4, MakeDigestPattern(0x11)));
        std::vector<std::byte> document = firstRecord;
        document.insert(document.end(), firstRecord.begin(), firstRecord.end());
        const auto result = LoadResumeState(
            std::span<const std::byte>(document), resourcePolicy);
        REQUIRE(result.HasValue());
        CHECK_FALSE(result.Value().hasTruncatedTail);
        CHECK(result.Value().completedSegments.size() == 1U);
    }

    // Identical wirehair cache duplicate vs same-ordinal different content.
    const std::vector<std::byte> cacheRecordBytes = WrapEnvelope(BuildWirehairBody(
        9, MakeCanonicalProfile().bytes,
        {{7U, {Byte(0x11), Byte(0x22)}}, {8U, {Byte(0x33)}}}));
    std::vector<std::byte> cacheDocument = cacheRecordBytes;
    cacheDocument.insert(cacheDocument.end(),
        cacheRecordBytes.begin(), cacheRecordBytes.end());
    const auto duplicateCacheResult = LoadResumeState(
        std::span<const std::byte>(cacheDocument), resourcePolicy);
    REQUIRE(duplicateCacheResult.HasValue());
    CHECK(duplicateCacheResult.Value().activeWirehairCaches.size() == 1U);

    {
        // Same ordinal, different valid content: re-serialize with a
        // corrected envelope so only the body differs between records.
        const std::vector<std::byte> validAltered = WrapEnvelope(BuildWirehairBody(
            9, [profileBytes = MakeCanonicalProfile().bytes]()
            {
                std::array<std::byte, 32> mutated = profileBytes;
                mutated[4] ^= Byte(0x80);
                return mutated;
            }(), {{7U, {Byte(0x11), Byte(0x22)}}, {8U, {Byte(0x33)}}}));
        std::vector<std::byte> conflictDocument = cacheRecordBytes;
        const std::size_t secondStart = conflictDocument.size();
        conflictDocument.insert(conflictDocument.end(),
            validAltered.begin(), validAltered.end());
        const auto conflictResult = LoadResumeState(
            std::span<const std::byte>(conflictDocument), resourcePolicy);
        CHECK_FALSE(conflictResult.HasValue());
        CHECK(conflictResult.Error().code == ProtocolErrorCode::ResumeRecordConflict);
        CHECK(conflictResult.Error().offset == secondStart);
    }

    // Cross-type ordinal overlap: completed vs either active cache type.
    {
        const std::vector<std::byte> completedRecord = WrapEnvelope(BuildCompletedBody(
            MakeSidAscending(), 8, 0, 4, MakeDigestPattern(0x11)));
        const std::vector<std::byte> wirehairRecord = WrapEnvelope(BuildWirehairBody(
            8, MakeCanonicalProfile().bytes, {{7U, {Byte(0x11)}}}));
        const std::vector<std::byte> directRecord = WrapEnvelope(BuildDirectRepeatBody(
            8, 4, {{2U, 3U, {Byte(0x01), Byte(0x02), Byte(0x00)}}}));

        auto checkConflict = [&](const std::span<const std::byte> first,
                                 const std::size_t firstSize,
                                 const std::span<const std::byte> second)
        {
            std::vector<std::byte> document(first.begin(), first.end());
            document.insert(document.end(), second.begin(), second.end());
            const auto result = LoadResumeState(
                std::span<const std::byte>(document), resourcePolicy);
            CHECK_FALSE(result.HasValue());
            CHECK(result.Error().code == ProtocolErrorCode::ResumeRecordConflict);
            CHECK(result.Error().offset == firstSize);
        };
        checkConflict(std::span<const std::byte>(completedRecord), completedRecord.size(),
                      std::span<const std::byte>(wirehairRecord));
        checkConflict(std::span<const std::byte>(completedRecord), completedRecord.size(),
                      std::span<const std::byte>(directRecord));
        // Reverse order: the cache ordinal is claimed first.
        checkConflict(std::span<const std::byte>(wirehairRecord), wirehairRecord.size(),
                      std::span<const std::byte>(completedRecord));
    }

    // Same outerBlockId inside one cache record: different payloads conflict,
    // identical payloads dedupe to the first occurrence.
    {
        const std::vector<std::byte> conflictingBody = BuildWirehairBody(
            12, MakeCanonicalProfile().bytes,
            {{7U, {Byte(0x0A), Byte(0x0B)}}, {7U, {Byte(0x0C), Byte(0x0D)}}});
        const auto conflictResult = LoadResumeState(
            std::span<const std::byte>(WrapEnvelope(std::span<const std::byte>(conflictingBody))),
            resourcePolicy);
        CHECK_FALSE(conflictResult.HasValue());
        CHECK(conflictResult.Error().code == ProtocolErrorCode::ResumeRecordConflict);

        const std::vector<std::byte> duplicateBody = BuildWirehairBody(
            12, MakeCanonicalProfile().bytes,
            {{7U, {Byte(0x0A), Byte(0x0B)}}, {9U, {Byte(0xFF)}},
             {7U, {Byte(0x0A), Byte(0x0B)}}});
        const auto duplicateResult = LoadResumeState(
            std::span<const std::byte>(WrapEnvelope(std::span<const std::byte>(duplicateBody))),
            resourcePolicy);
        REQUIRE(duplicateResult.HasValue());
        REQUIRE(duplicateResult.Value().activeWirehairCaches.size() == 1U);
        const auto& entries = duplicateResult.Value().activeWirehairCaches[0].entries;
        REQUIRE(entries.size() == 2U);
        CHECK(entries[0].outerBlockId == 7U);
        CHECK(entries[1].outerBlockId == 9U);
    }

    // Same blockOrdinal inside one DirectRepeat record: different entries
    // conflict, identical entries dedupe.
    {
        const std::vector<std::byte> conflictingBody = BuildDirectRepeatBody(
            13, 4, {{2U, 3U, {Byte(0x01), Byte(0x02), Byte(0x00)}},
                    {2U, 2U, {Byte(0x03), Byte(0x00)}}});
        const auto conflictResult = LoadResumeState(
            std::span<const std::byte>(WrapEnvelope(std::span<const std::byte>(conflictingBody))),
            resourcePolicy);
        CHECK_FALSE(conflictResult.HasValue());
        CHECK(conflictResult.Error().code == ProtocolErrorCode::ResumeRecordConflict);

        const std::vector<std::byte> duplicateBody = BuildDirectRepeatBody(
            13, 4, {{2U, 3U, {Byte(0x01), Byte(0x02), Byte(0x00)}},
                    {2U, 3U, {Byte(0x01), Byte(0x02), Byte(0x00)}}});
        const auto duplicateResult = LoadResumeState(
            std::span<const std::byte>(WrapEnvelope(std::span<const std::byte>(duplicateBody))),
            resourcePolicy);
        REQUIRE(duplicateResult.HasValue());
        REQUIRE(duplicateResult.Value().activeDirectRepeatRecords.size() == 1U);
        CHECK(duplicateResult.Value()
                .activeDirectRepeatRecords[0].entries.size() == 1U);
    }
}

TEST_CASE("Field boundary matrix pins codes and offsets", "[pbprotocol][resume-state]")
{
    const ReceiverResourcePolicy policy = MakeBoundaryPolicy();
    REQUIRE(static_cast<bool>(ValidateReceiverResourcePolicy(policy)));

    // Completed rawSize around the maxRawSegmentBytes bound.
    for (const std::uint64_t rawSize : {0ULL, 1ULL, 99ULL, 100ULL, 101ULL})
    {
        const std::vector<std::byte> document = WrapEnvelope(BuildCompletedBody(
            MakeSidAscending(), 1, 0, rawSize, MakeDigestPattern(0x20)));
        const auto result = LoadResumeState(
            std::span<const std::byte>(document), policy);
        if (rawSize == 0U)
        {
            CHECK(result.Error().code == ProtocolErrorCode::InvalidRecordSize);
            CHECK(result.Error().offset == 14U);
        }
        else if (rawSize > 100ULL)
        {
            CHECK(result.Error().code == ProtocolErrorCode::ResourceLimitExceeded);
            CHECK(result.Error().offset == 14U);
        }
        else
        {
            REQUIRE(result.HasValue());
            CHECK_FALSE(result.Value().hasTruncatedTail);
        }
    }

    // rawOffset + rawSize around maxAcceptedFileBytes (256).
    const auto checkCompletedSum = [&](const std::uint64_t rawOffset,
                                       const std::uint64_t rawSize)
    {
        return LoadResumeState(std::span<const std::byte>(WrapEnvelope(
            BuildCompletedBody(MakeSidAscending(), 1, rawOffset, rawSize,
                               MakeDigestPattern(0x20)))), policy);
    };
    REQUIRE(static_cast<bool>(checkCompletedSum(249ULL, 7ULL)));      // sum == 256
    CHECK(checkCompletedSum(250ULL, 7ULL).Error().code
        == ProtocolErrorCode::ResourceLimitExceeded);                 // sum 257

    // Checked-add overflow sentinel: offset + size must not wrap.
    const auto overflowResult = checkCompletedSum(
        std::numeric_limits<std::uint64_t>::max(), 1ULL);
    CHECK_FALSE(static_cast<bool>(overflowResult));
    CHECK(overflowResult.Error().code == ProtocolErrorCode::LengthOverflow);

    // Wirehair entry payload length around maxOuterBlockBytes (32).
    for (const std::size_t payloadSize : {1U, 31U, 32U, 33U})
    {
        const std::vector<std::byte> document = WrapEnvelope(BuildWirehairBody(
            4, MakeCanonicalProfile().bytes,
            {{7U, std::vector<std::byte>(payloadSize, Byte(0x41))}}));
        const auto result = LoadResumeState(
            std::span<const std::byte>(document), policy);
        if (payloadSize > 32U)
        {
            CHECK(result.Error().code == ProtocolErrorCode::ResourceLimitExceeded);
            CHECK(result.Error().offset == 14U + kWirehairHeaderBodySize + 4U);
        }
        else
        {
            REQUIRE(result.HasValue());
            CHECK_FALSE(result.Value().hasTruncatedTail);
        }
    }

    // DirectRepeat block count around maxDirectRepeatBlockCount (8).
    for (const std::uint32_t directBlockCount : {0U, 1U, 7U, 8U, 9U})
    {
        const auto buildEntry = [&directBlockCount]()
        {
            std::vector<std::tuple<std::uint32_t, std::uint32_t, std::vector<std::byte>>> entries;
            if (directBlockCount > 0U)
            {
                entries.emplace_back(0U, 1U, std::vector<std::byte>{Byte(0x63)});
            }
            return entries;
        };
        const std::vector<std::byte> document = WrapEnvelope(BuildDirectRepeatBody(
            4, directBlockCount, buildEntry()));
        const auto result = LoadResumeState(
            std::span<const std::byte>(document), policy);
        if (directBlockCount == 0U)
        {
            CHECK(result.Error().code == ProtocolErrorCode::InvalidRecordSize);
            CHECK(result.Error().offset == 14U + 9U);
        }
        else if (directBlockCount > 8U)
        {
            CHECK(result.Error().code == ProtocolErrorCode::ResourceLimitExceeded);
            CHECK(result.Error().offset == 14U + 9U);
        }
        else
        {
            REQUIRE(result.HasValue());
            CHECK_FALSE(result.Value().hasTruncatedTail);
        }
    }

    // blockOrdinal equal to the declared count is out of range.
    {
        const std::vector<std::byte> document = WrapEnvelope(BuildDirectRepeatBody(
            4, 3, {{3U, 1U, {Byte(0x63)}}}));
        const auto result = LoadResumeState(
            std::span<const std::byte>(document), policy);
        CHECK_FALSE(static_cast<bool>(result));
        CHECK(result.Error().code == ProtocolErrorCode::SegmentOrdinalOutOfRange);
        CHECK(result.Error().offset == 14U + kDirectRepeatHeaderBodySize);

        const std::vector<std::byte> atBoundary = WrapEnvelope(BuildDirectRepeatBody(
            4, 3, {{2U, 1U, {Byte(0x63)}}}));
        REQUIRE(static_cast<bool>(LoadResumeState(
            std::span<const std::byte>(atBoundary), policy)));
    }

    // realPayloadBytes / paddedLen consistency and bound checks.
    struct DirectRepeatFieldCase
    {
        std::uint32_t realPayloadBytes;
        std::size_t paddedBytes;
        bool expectSuccess;
        ProtocolErrorCode code;
        // Failure offset relative to the document start (0 when unused).
        std::size_t expectedOffset;
    };
    const std::vector<DirectRepeatFieldCase> cases{
        {0U, 4U, false, ProtocolErrorCode::InvalidRecordSize, 14U + 21U},
        {1U, 0U, false, ProtocolErrorCode::InvalidRecordSize, 14U + 21U},
        {5U, 4U, false, ProtocolErrorCode::InvalidRecordSize, 14U + 21U},
        {4U, 4U, true, ProtocolErrorCode::None, 0U},
        {32U, 32U, true, ProtocolErrorCode::None, 0U},
        {1U, 33U, false, ProtocolErrorCode::ResourceLimitExceeded, 14U + 25U}};

    for (const auto& testCase : cases)
    {
        std::vector<std::byte> paddedPayload(testCase.paddedBytes);
        for (std::size_t byteIndex = 0; byteIndex < paddedPayload.size(); byteIndex++)
        {
            paddedPayload[byteIndex] = byteIndex < static_cast<size_t>(testCase.realPayloadBytes)
                ? Byte(0x5A) : std::byte{0};
        }
        const std::vector<std::byte> document = WrapEnvelope(BuildDirectRepeatBody(
            4, 3, {{1U, testCase.realPayloadBytes, paddedPayload}}));
        const auto result = LoadResumeState(
            std::span<const std::byte>(document), policy);
        if (testCase.expectSuccess)
        {
            REQUIRE(result.HasValue());
            CHECK_FALSE(result.Value().hasTruncatedTail);
        }
        else
        {
            CHECK_FALSE(static_cast<bool>(result));
            CHECK(result.Error().code == testCase.code);
            CHECK(result.Error().offset == testCase.expectedOffset);
        }
    }
}

TEST_CASE("Envelope v1 passthrough and document budget gates", "[pbprotocol][resume-state]")
{
    const ReceiverResourcePolicy resourcePolicy = MakeTestPolicy(4096);

    // The single-record API still accepts any legacy payload (passthrough),
    // while the document loader rejects unknown typed bodies fail-closed.
    std::vector<std::byte> legacyPayload(24, Byte(0x7F));
    for (std::size_t byteIndex = 1U; byteIndex < legacyPayload.size(); byteIndex++)
    {
        legacyPayload[byteIndex] = Byte(static_cast<std::uint8_t>(byteIndex * 3U));
    }
    const std::vector<std::byte> legacyDocument = WrapEnvelope(
        std::span<const std::byte>(legacyPayload));
    const auto passthroughResult = ParseResumeRecord(
        std::span<const std::byte>(legacyDocument), resourcePolicy);
    REQUIRE(passthroughResult.HasValue());
    CHECK(passthroughResult.Value() == legacyPayload);

    const auto documentResult = LoadResumeState(
        std::span<const std::byte>(legacyDocument), resourcePolicy);
    CHECK_FALSE(static_cast<bool>(documentResult));
    CHECK(documentResult.Error().code == ProtocolErrorCode::InvalidEnumValue);
    CHECK(documentResult.Error().offset == 14U);

    // Whole-document budget gate: exact fit passes, one byte over fails before
    // any parsing; a valid document plus a torn extra byte stays loadable.
    const ReceiverResourcePolicy exactFitPolicy = MakeTestPolicy(kD4.size());
    REQUIRE(static_cast<bool>(LoadResumeState(
        std::span<const std::byte>(kD4), exactFitPolicy)));

    std::vector<std::byte> paddedDocument(kD4.begin(), kD4.end());
    paddedDocument.push_back(Byte(0x5A));
    const ReceiverResourcePolicy oneOverPolicy = MakeTestPolicy(paddedDocument.size());
    REQUIRE(static_cast<bool>(LoadResumeState(
        std::span<const std::byte>(paddedDocument), oneOverPolicy)));
    CHECK(LoadResumeState(std::span<const std::byte>(paddedDocument), oneOverPolicy)
              .Value().hasTruncatedTail);

    const ReceiverResourcePolicy overBudgetPolicy = MakeTestPolicy(kD4.size());
    const auto overResult = LoadResumeState(
        std::span<const std::byte>(paddedDocument), overBudgetPolicy);
    CHECK_FALSE(static_cast<bool>(overResult));
    CHECK(overResult.Error().code == ProtocolErrorCode::ResourceLimitExceeded);
    CHECK(overResult.Error().offset == 0U);

    // A document of pure garbage above the budget must fail with the quota
    // code, never a parser code.
    std::vector<std::byte> garbageDocument(paddedDocument.size(), Byte(0x13));
    const auto garbageOver = LoadResumeState(
        std::span<const std::byte>(garbageDocument), overBudgetPolicy);
    CHECK_FALSE(static_cast<bool>(garbageOver));
    CHECK(garbageOver.Error().code == ProtocolErrorCode::ResourceLimitExceeded);

    // Invalid resource policy outranks every other check, even on empty input.
    const ReceiverResourcePolicy zeroPolicy{};
    for (const std::span<const std::byte> document : {
             std::span<const std::byte>{},
             std::span<const std::byte>(kD4),
             std::span<const std::byte>(garbageDocument)})
    {
        const auto result = LoadResumeState(document, zeroPolicy);
        CHECK_FALSE(static_cast<bool>(result));
        CHECK(result.Error().code == ProtocolErrorCode::InvalidResourcePolicy);
        CHECK(result.Error().offset == 0U);
    }

    // ValidateResumeStateBudget boundary behaviour.
    REQUIRE(static_cast<bool>(ValidateResumeStateBudget(0ULL, resourcePolicy)));
    REQUIRE(static_cast<bool>(
        ValidateResumeStateBudget(resourcePolicy.maxResumeBytes, resourcePolicy)));
    const auto overBudget =
        ValidateResumeStateBudget(resourcePolicy.maxResumeBytes + 1ULL, resourcePolicy);
    CHECK_FALSE(static_cast<bool>(overBudget));
    CHECK(overBudget.Error().code == ProtocolErrorCode::ResourceLimitExceeded);
}

// Loader completed-count quota gate: one record beyond maxSegmentCount fails the
// whole document with ResourceLimitExceeded at that record's start - no partial
// state is ever returned. Identical duplicates dedupe before the gate is
// consulted, so they never trip it (key scans precede the count check; the
// builder mirrors this precedence).
TEST_CASE("Completed-count quota gate pins code and offset", "[pbprotocol][resume-state]")
{
    ReceiverResourcePolicy resourcePolicy = MakeBoundaryPolicy();
    resourcePolicy.maxSegmentCount = 2U;
    REQUIRE(static_cast<bool>(ValidateReceiverResourcePolicy(resourcePolicy)));

    const std::vector<std::byte> recordOne = WrapEnvelope(
        std::span<const std::byte>(BuildCompletedBody(MakeSidAscending(), 1, 0, 7, MakeDigestPattern(0x20))));
    const std::vector<std::byte> recordTwo = WrapEnvelope(
        std::span<const std::byte>(BuildCompletedBody(MakeSidAscending(), 2, 0, 8, MakeDigestPattern(0x30))));
    const std::vector<std::byte> recordThree = WrapEnvelope(
        std::span<const std::byte>(BuildCompletedBody(MakeSidAscending(), 3, 0, 9, MakeDigestPattern(0x40))));

    // Sanity: exactly at the quota (two records) still loads.
    {
        std::vector<std::byte> atQuotaDocument = recordOne;
        atQuotaDocument.insert(atQuotaDocument.end(), recordTwo.begin(), recordTwo.end());
        const auto loadResult = LoadResumeState(
            std::span<const std::byte>(atQuotaDocument), resourcePolicy);
        REQUIRE(static_cast<bool>(loadResult));
        CHECK_FALSE(loadResult.Value().hasTruncatedTail);
        CHECK(loadResult.Value().completedSegments.size() == 2U);
    }

    // One record beyond the quota: fail-closed at that record's start offset.
    {
        std::vector<std::byte> overQuotaDocument = recordOne;
        overQuotaDocument.insert(overQuotaDocument.end(), recordTwo.begin(), recordTwo.end());
        overQuotaDocument.insert(overQuotaDocument.end(), recordThree.begin(), recordThree.end());
        const auto loadResult = LoadResumeState(
            std::span<const std::byte>(overQuotaDocument), resourcePolicy);
        CHECK_FALSE(static_cast<bool>(loadResult));
        CHECK(loadResult.Error().code == ProtocolErrorCode::ResourceLimitExceeded);
        CHECK(loadResult.Error().offset == 182U); // two fixed-layout 91-byte records.
    }

    // Dedup precedes the gate: an identical duplicate never consumes quota.
    {
        std::vector<std::byte> duplicateAtQuotaDocument = recordOne;
        duplicateAtQuotaDocument.insert(duplicateAtQuotaDocument.end(), recordTwo.begin(), recordTwo.end());
        duplicateAtQuotaDocument.insert(duplicateAtQuotaDocument.end(), recordOne.begin(), recordOne.end());
        const auto loadResult = LoadResumeState(
            std::span<const std::byte>(duplicateAtQuotaDocument), resourcePolicy);
        REQUIRE(static_cast<bool>(loadResult));
        CHECK_FALSE(loadResult.Value().hasTruncatedTail);
        CHECK(loadResult.Value().completedSegments.size() == 2U);
    }
}

TEST_CASE("Active-cache records share the segment quota gate", "[pbprotocol][resume-state]")
{
    ReceiverResourcePolicy resourcePolicy = MakeBoundaryPolicy();
    resourcePolicy.maxSegmentCount = 2U;
    REQUIRE(static_cast<bool>(ValidateReceiverResourcePolicy(resourcePolicy)));

    const std::vector<std::byte> wirehairRecord = WrapEnvelope(
        BuildWirehairBody(5, MakeCanonicalProfile().bytes, {}));
    const std::vector<std::byte> directRecord = WrapEnvelope(
        BuildDirectRepeatBody(7, 4U, {}));
    const std::vector<std::byte> completedRecord = WrapEnvelope(
        BuildCompletedBody(MakeSidAscending(), 9, 0, 7, MakeDigestPattern(0x20)));

    // Sanity: the exact frame sizes pin the offsets asserted below.
    REQUIRE(wirehairRecord.size() == 63U);
    REQUIRE(directRecord.size() == 35U);
    REQUIRE(completedRecord.size() == 91U);

    // The quota spans categories: one wirehair plus one direct reaches it.
    {
        std::vector<std::byte> document = wirehairRecord;
        document.insert(document.end(), directRecord.begin(), directRecord.end());
        const auto loadResult = LoadResumeState(
            std::span<const std::byte>(document), resourcePolicy);
        REQUIRE(static_cast<bool>(loadResult));
        CHECK_FALSE(loadResult.Value().hasTruncatedTail);
        CHECK(loadResult.Value().activeWirehairCaches.size() == 1U);
        CHECK(loadResult.Value().activeDirectRepeatRecords.size() == 1U);
    }

    // A third distinct record of any category fails at its own start offset.
    {
        std::vector<std::byte> document = wirehairRecord;
        document.insert(document.end(), directRecord.begin(), directRecord.end());
        document.insert(document.end(), completedRecord.begin(), completedRecord.end());
        const auto loadResult = LoadResumeState(
            std::span<const std::byte>(document), resourcePolicy);
        CHECK_FALSE(static_cast<bool>(loadResult));
        CHECK(loadResult.Error().code == ProtocolErrorCode::ResourceLimitExceeded);
        CHECK(loadResult.Error().offset == 98U); // 63 + 35.
    }

    // Symmetric direction: a completed record first, then an active cache fills
    // the remaining quota and any further distinct record is rejected. Guards
    // against a per-category-only gate in either direction.
    {
        std::vector<std::byte> document = completedRecord;
        document.insert(document.end(), wirehairRecord.begin(), wirehairRecord.end());
        const auto firstLoadResult = LoadResumeState(
            std::span<const std::byte>(document), resourcePolicy);
        REQUIRE(static_cast<bool>(firstLoadResult));
        CHECK(firstLoadResult.Value().completedSegments.size() == 1U);
        CHECK(firstLoadResult.Value().activeWirehairCaches.size() == 1U);

        document.insert(document.end(), directRecord.begin(), directRecord.end());
        const auto secondLoadResult = LoadResumeState(
            std::span<const std::byte>(document), resourcePolicy);
        CHECK_FALSE(static_cast<bool>(secondLoadResult));
        CHECK(secondLoadResult.Error().code == ProtocolErrorCode::ResourceLimitExceeded);
        CHECK(secondLoadResult.Error().offset == 91U + 63U);
    }

    // Duplicates never consume quota regardless of the category mix.
    {
        std::vector<std::byte> document = wirehairRecord;
        document.insert(document.end(), directRecord.begin(), directRecord.end());
        document.insert(document.end(), wirehairRecord.begin(), wirehairRecord.end());
        const auto loadResult = LoadResumeState(
            std::span<const std::byte>(document), resourcePolicy);
        REQUIRE(static_cast<bool>(loadResult));
        CHECK_FALSE(loadResult.Value().hasTruncatedTail);
        CHECK(loadResult.Value().activeWirehairCaches.size() == 1U);
        CHECK(loadResult.Value().activeDirectRepeatRecords.size() == 1U);
    }
}


// Single-record envelope pins (ported from the superseded pre-record-type
// suite): serialize capacity handling and the full truncation sweep at
// every record boundary stay covered after that file was retired.
TEST_CASE("Single-record envelope pins capacity and truncation at every boundary",
          "[pbprotocol][resume-state]")
{
    const ReceiverResourcePolicy resourcePolicy = MakeTestPolicy(1024);

    // An empty payload produces exactly one 18-byte envelope and round-trips.
    const std::span<const std::byte> emptyPayload{};
    std::vector<std::byte> emptyRecord(kResumeRecordEnvelopeBytes);
    REQUIRE(static_cast<bool>(SerializeResumeRecord(
        emptyPayload, std::span<std::byte>(emptyRecord))));
    const auto emptyParseResult = ParseResumeRecord(
        std::span<const std::byte>(emptyRecord), resourcePolicy);
    REQUIRE(emptyParseResult.HasValue());
    CHECK(emptyParseResult.Value().empty());

    // A non-empty payload round-trips byte-exactly.
    std::vector<std::byte> payload(32U);
    for (std::size_t byteIndex = 0; byteIndex < payload.size(); byteIndex++)
    {
        payload[byteIndex] = Byte(static_cast<std::uint8_t>(0x61U + byteIndex % 26U));
    }
    std::vector<std::byte> record(kResumeRecordEnvelopeBytes + payload.size());
    REQUIRE(static_cast<bool>(SerializeResumeRecord(
        std::span<const std::byte>(payload), std::span<std::byte>(record))));
    const auto parseResult = ParseResumeRecord(
        std::span<const std::byte>(record), resourcePolicy);
    REQUIRE(parseResult.HasValue());
    CHECK(parseResult.Value() == payload);

    // Extra trailing capacity is left untouched by the serializer.
    std::vector<std::byte> shortPayload(4U, Byte(0x62));
    std::vector<std::byte> oversizedOutput(kResumeRecordEnvelopeBytes + 16U, Byte(0xEE));
    REQUIRE(static_cast<bool>(SerializeResumeRecord(
        std::span<const std::byte>(shortPayload), std::span<std::byte>(oversizedOutput))));
    const std::size_t writtenBytes = kResumeRecordEnvelopeBytes + shortPayload.size();
    for (std::size_t byteIndex = writtenBytes; byteIndex < oversizedOutput.size(); byteIndex++)
    {
        CHECK(oversizedOutput[byteIndex] == Byte(0xEE));
    }

    // A too-small output buffer fails without touching the buffer.
    std::vector<std::byte> smallOutput(writtenBytes - 1U, Byte(0x77));
    const auto smallStatus = SerializeResumeRecord(
        std::span<const std::byte>(shortPayload), std::span<std::byte>(smallOutput));
    REQUIRE_FALSE(static_cast<bool>(smallStatus));
    CHECK(smallStatus.Error().code == ProtocolErrorCode::OutputBufferTooSmall);
    for (const std::byte bufferByte : smallOutput)
    {
        CHECK(bufferByte == Byte(0x77));
    }

    // Every proper prefix of a record is truncated input.
    for (std::size_t prefixLength = 0; prefixLength < record.size(); prefixLength++)
    {
        const auto truncatedResult = ParseResumeRecord(
            std::span<const std::byte>(record.data(), prefixLength), resourcePolicy);
        REQUIRE_FALSE(truncatedResult.HasValue());
        CHECK(truncatedResult.Error().code == ProtocolErrorCode::TruncatedInput);
    }
}

// Large-N identical duplicate entry sets exercise the dedup helpers
// auxiliary allocation paths (order index vector + drop mask). Dedup is
// best-effort under allocation failure, but on the happy path a record
// with many identical duplicate entries must load and collapse to one
// entry per distinct id, keeping the first occurrence.
TEST_CASE("Large identical duplicate entry sets dedupe to one entry per id",
          "[pbprotocol][resume-state]")
{
    const ReceiverResourcePolicy resourcePolicy = MakeTestPolicy(1U << 20);
    const std::uint32_t entryCount = 4096U;

    {
        std::vector<std::pair<std::uint32_t, std::vector<std::byte>>> wirehairEntries;
        wirehairEntries.reserve(entryCount);
        for (std::uint32_t entryIndex = 0; entryIndex < entryCount; entryIndex++)
        {
            wirehairEntries.emplace_back(5U, std::vector<std::byte>{Byte(0xA5)});
        }
        const std::vector<std::byte> wirehairDocument = WrapEnvelope(BuildWirehairBody(
            3, MakeCanonicalProfile().bytes, wirehairEntries));
        const auto wirehairResult = LoadResumeState(
            std::span<const std::byte>(wirehairDocument), resourcePolicy);
        REQUIRE(wirehairResult.HasValue());
        CHECK_FALSE(wirehairResult.Value().hasTruncatedTail);
        CHECK(wirehairResult.Value().activeWirehairCaches.size() == 1U);
        CHECK(wirehairResult.Value().activeWirehairCaches.front().entries.size() == 1U);
        CHECK(wirehairResult.Value().activeWirehairCaches.front().entries.front().outerBlockId == 5U);
        CHECK(wirehairResult.Value().activeWirehairCaches.front().entries.front().payload.size() == 1U);
    }

    {
        std::vector<std::tuple<std::uint32_t, std::uint32_t, std::vector<std::byte>>> directEntries;
        directEntries.reserve(entryCount);
        for (std::uint32_t entryIndex = 0; entryIndex < entryCount; entryIndex++)
        {
            directEntries.emplace_back(2U, 1U, std::vector<std::byte>{Byte(0xA5)});
        }
        const std::vector<std::byte> directDocument = WrapEnvelope(BuildDirectRepeatBody(
            3, 4, directEntries));
        const auto directResult = LoadResumeState(
            std::span<const std::byte>(directDocument), resourcePolicy);
        REQUIRE(directResult.HasValue());
        CHECK_FALSE(directResult.Value().hasTruncatedTail);
        CHECK(directResult.Value().activeDirectRepeatRecords.size() == 1U);
        CHECK(directResult.Value().activeDirectRepeatRecords.front().entries.size() == 1U);
        CHECK(directResult.Value().activeDirectRepeatRecords.front().entries.front().blockOrdinal == 2U);
        CHECK(directResult.Value().activeDirectRepeatRecords.front().entries.front().realPayloadBytes == 1U);
    }
}
} // namespace
