add_executable(PBDesktopLevelsMutation desktop_levels_mutation.cpp)
target_link_libraries(PBDesktopLevelsMutation PRIVATE PB::CompilerSettings PB::PBDesktopLevelsReference PB::PBProtocol)
add_dependencies(PBParserFuzzHarness PBDesktopLevelsMutation)

foreach(desktopTarget IN ITEMS PBDesktopLevelsReference PBDesktopLevelsMutation PBDesktopLevelsBaseline)
    if(NOT TARGET ${desktopTarget})
        continue()
    endif()
    get_target_property(desktopTargetType ${desktopTarget} TYPE)
    if(MSVC)
        target_compile_options(${desktopTarget} PRIVATE /Zi /fsanitize=address)
        target_compile_definitions(${desktopTarget} PRIVATE _DISABLE_STRING_ANNOTATION _DISABLE_VECTOR_ANNOTATION)
        if(desktopTargetType STREQUAL "EXECUTABLE")
            target_link_options(${desktopTarget} PRIVATE /DEBUG /INCREMENTAL:NO)
            get_filename_component(desktopCompilerDirectory "${CMAKE_CXX_COMPILER}" DIRECTORY)
            if(desktopTarget STREQUAL "PBDesktopLevelsMutation")
                add_custom_command(TARGET ${desktopTarget} POST_BUILD COMMAND "${CMAKE_COMMAND}" -E copy_if_different
                    "${desktopCompilerDirectory}/clang_rt.asan_dynamic-x86_64.dll" "$<TARGET_FILE_DIR:${desktopTarget}>" VERBATIM)
            else()
                add_custom_target(PBDesktopLevelsBaselineAsanRuntime ALL COMMAND "${CMAKE_COMMAND}" -E copy_if_different
                    "${desktopCompilerDirectory}/clang_rt.asan_dynamic-x86_64.dll" "$<TARGET_FILE_DIR:${desktopTarget}>"
                    DEPENDS ${desktopTarget} VERBATIM)
            endif()
        endif()
    elseif(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
        target_compile_options(${desktopTarget} PRIVATE -fno-omit-frame-pointer -fsanitize=address,undefined)
        if(desktopTargetType STREQUAL "EXECUTABLE")
            target_link_options(${desktopTarget} PRIVATE -fsanitize=address,undefined)
        endif()
    endif()
endforeach()
unset(desktopTarget)
unset(desktopTargetType)
unset(desktopCompilerDirectory)

if(BUILD_TESTING)
    add_test(NAME PBDesktopLevelsMutationSmoke COMMAND PBDesktopLevelsMutation 384)
    set_tests_properties(PBDesktopLevelsMutationSmoke PROPERTIES LABELS "desktop-levels;mutation" TIMEOUT 180
        PASS_REGULAR_EXPRESSION "DESKTOP_LEVELS_MUTATION_COMPLETED")
    foreach(seed IN ITEMS clean2 clean4 phase-pilot ladder short-output overflow-view budget clipped-tile)
        add_test(NAME "PBDesktopLevelsCorpus.${seed}" COMMAND PBDesktopLevelsMutation --input "${CMAKE_CURRENT_SOURCE_DIR}/corpus/desktop-levels/${seed}.bin")
        set_tests_properties("PBDesktopLevelsCorpus.${seed}" PROPERTIES LABELS "desktop-levels;mutation;corpus" TIMEOUT 30
            PASS_REGULAR_EXPRESSION "DESKTOP_LEVELS_CORPUS_VALIDATED")
    endforeach()
endif()
