if(NOT DEFINED PB_ENCODER OR NOT DEFINED PB_EVIDENCE_ROOT OR
        NOT DEFINED PB_MONITOR_ORIGIN_X OR NOT DEFINED PB_MONITOR_ORIGIN_Y)
    message(FATAL_ERROR "PB_ENCODER, PB_EVIDENCE_ROOT and explicit PB_MONITOR_ORIGIN_X/Y are required")
endif()
foreach(pbCoordinate IN ITEMS PB_MONITOR_ORIGIN_X PB_MONITOR_ORIGIN_Y)
    if(NOT "${${pbCoordinate}}" MATCHES "^(0|-?[1-9][0-9]*)$")
        message(FATAL_ERROR "${pbCoordinate} must be a signed decimal physical desktop coordinate")
    endif()
    string(LENGTH "${${pbCoordinate}}" pbCoordinateLength)
    if(pbCoordinateLength GREATER 11)
        message(FATAL_ERROR "${pbCoordinate} is outside the signed 32-bit physical desktop coordinate range")
    endif()
    if(${${pbCoordinate}} LESS -2147483648 OR ${${pbCoordinate}} GREATER 2147483647)
        message(FATAL_ERROR "${pbCoordinate} is outside the signed 32-bit physical desktop coordinate range")
    endif()
endforeach()
string(RANDOM LENGTH 24 ALPHABET 0123456789abcdef pbArtifactSuffix)
set(pbArtifactDirectory "${PB_EVIDENCE_ROOT}/encoder-local-desktop-${pbArtifactSuffix}")
if(EXISTS "${pbArtifactDirectory}")
    message(FATAL_ERROR "Encoder test artifact path already exists")
endif()
file(MAKE_DIRECTORY "${pbArtifactDirectory}")

# These rejection paths must stop before a telemetry file or data window is
# created. They exercise the executable's real parser, not a duplicated model.
foreach(pbInvalidArguments IN ITEMS
        "--visual"
        "--visual|unknown"
        "--visual|local-desktop-bootstrap|--visual|local-desktop-bootstrap"
        "--visual|local-desktop-bootstrap|--data-window|--data-window"
        "--visual|local-desktop-bootstrap|--frames|1|--frames|2")
    string(REPLACE "|" ";" pbArguments "${pbInvalidArguments}")
    set(pbRejectedTelemetry "${pbArtifactDirectory}/must-not-exist.jsonl")
    execute_process(
        COMMAND "${PB_ENCODER}" ${pbArguments} --telemetry "${pbRejectedTelemetry}"
        RESULT_VARIABLE pbExit OUTPUT_VARIABLE pbOutput ERROR_VARIABLE pbError TIMEOUT 10)
    if(NOT pbExit STREQUAL "2" OR EXISTS "${pbRejectedTelemetry}")
        message(FATAL_ERROR "Encoder accepted invalid visual arguments or created telemetry: ${pbInvalidArguments}\n${pbExit}\n${pbOutput}\n${pbError}")
    endif()
endforeach()

foreach(pbEntryMode IN ITEMS implicit explicit)
    set(pbArguments --visual local-desktop-bootstrap --origin "${PB_MONITOR_ORIGIN_X}" "${PB_MONITOR_ORIGIN_Y}")
    if(pbEntryMode STREQUAL "explicit")
        list(APPEND pbArguments --data-window)
    endif()
    set(pbTelemetry "${pbArtifactDirectory}/${pbEntryMode}-呈现.jsonl")
    execute_process(
        COMMAND "${PB_ENCODER}" ${pbArguments} --frames 12 --telemetry "${pbTelemetry}"
        RESULT_VARIABLE pbExit OUTPUT_VARIABLE pbOutput ERROR_VARIABLE pbError TIMEOUT 30)
    file(WRITE "${pbArtifactDirectory}/${pbEntryMode}-stdout.json" "${pbOutput}")
    file(WRITE "${pbArtifactDirectory}/${pbEntryMode}-stderr.txt" "${pbError}")
    if(NOT pbExit STREQUAL "0")
        message(FATAL_ERROR "Encoder LocalDesktop ${pbEntryMode} entry failed: ${pbExit}\n${pbOutput}\n${pbError}")
    endif()
    foreach(pbField IN ITEMS submittedFrames totalPresentCalls totalSuccessfulPresents discardedEpochFrames replacedPendingFrames)
        string(JSON ${pbField} GET "${pbOutput}" ${pbField})
    endforeach()
    math(EXPR pbAccounted "${totalSuccessfulPresents}+${discardedEpochFrames}+${replacedPendingFrames}")
    if(NOT submittedFrames EQUAL 12 OR totalPresentCalls LESS 1 OR NOT totalPresentCalls EQUAL totalSuccessfulPresents OR NOT pbAccounted EQUAL submittedFrames)
        message(FATAL_ERROR "LocalDesktop entry changed finite submission/presentation accounting: ${pbOutput}")
    endif()
    foreach(pbField IN ITEMS candidateContractSatisfied perMonitorV2 latencyWaitable bgraUnorm noMsaa alphaIgnored scalingNone tearingDisabled)
        string(JSON pbValue GET "${pbOutput}" ${pbField})
        if(NOT pbValue)
            message(FATAL_ERROR "LocalDesktop native contract ${pbField} was false: ${pbOutput}")
        endif()
    endforeach()
    foreach(pbField IN ITEMS pendingFrame inFlightFrame softwareRasterizer)
        string(JSON pbValue GET "${pbOutput}" ${pbField})
        if(pbValue)
            message(FATAL_ERROR "Unexpected LocalDesktop final state ${pbField}: ${pbOutput}")
        endif()
    endforeach()
    string(JSON pbBufferCount GET "${pbOutput}" bufferCount)
    string(JSON pbLatency GET "${pbOutput}" maximumFrameLatency)
    string(JSON pbWidth GET "${pbOutput}" DataWindowPhysicalSize 0)
    string(JSON pbHeight GET "${pbOutput}" DataWindowPhysicalSize 1)
    string(JSON pbOriginX GET "${pbOutput}" clientOrigin 0)
    string(JSON pbOriginY GET "${pbOutput}" clientOrigin 1)
    if(NOT pbBufferCount EQUAL 2 OR NOT pbLatency EQUAL 1 OR NOT pbWidth EQUAL 1920 OR NOT pbHeight EQUAL 1080)
        message(FATAL_ERROR "LocalDesktop entry changed the data-window contract: ${pbOutput}")
    endif()
    if(NOT pbOriginX EQUAL PB_MONITOR_ORIGIN_X OR NOT pbOriginY EQUAL PB_MONITOR_ORIGIN_Y)
        message(FATAL_ERROR "LocalDesktop entry did not use the explicitly configured physical test origin: ${pbOutput}")
    endif()
    string(JSON pbVisualType TYPE "${pbOutput}" PresentedVisualFPS)
    if(NOT pbVisualType STREQUAL "NUMBER" AND NOT pbVisualType STREQUAL "NULL")
        message(FATAL_ERROR "Invalid PresentedVisualFPS representation: ${pbOutput}")
    endif()
    file(STRINGS "${pbTelemetry}" pbTelemetryLines ENCODING UTF-8)
    list(LENGTH pbTelemetryLines pbLineCount)
    if(pbLineCount LESS 1)
        message(FATAL_ERROR "LocalDesktop entry produced no telemetry")
    endif()
    foreach(pbLine IN LISTS pbTelemetryLines)
        string(JSON pbSchema GET "${pbLine}" schema_version)
        if(NOT pbSchema EQUAL 1)
            message(FATAL_ERROR "LocalDesktop entry changed the presentation telemetry schema")
        endif()
    endforeach()
    file(SHA256 "${pbTelemetry}" pbBeforeDigest)
    execute_process(
        COMMAND "${PB_ENCODER}" ${pbArguments} --frames 1 --telemetry "${pbTelemetry}"
        RESULT_VARIABLE pbOverwriteExit OUTPUT_VARIABLE pbOverwriteOutput ERROR_VARIABLE pbOverwriteError TIMEOUT 10)
    file(SHA256 "${pbTelemetry}" pbAfterDigest)
    if(NOT pbOverwriteExit STREQUAL "1" OR NOT pbBeforeDigest STREQUAL pbAfterDigest)
        message(FATAL_ERROR "LocalDesktop telemetry overwrite was not rejected immutably: ${pbOverwriteExit}\n${pbOverwriteOutput}\n${pbOverwriteError}")
    endif()
endforeach()

file(WRITE "${pbArtifactDirectory}/gate.txt"
    "PASS: explicit and implicit data-window entries perform 12 bounded LocalDesktop Bootstrap CPU submissions and actual native Presents; native window/telemetry/no-overwrite contracts retained.\nThis entry gate does not claim captured Bootstrap decoding or equate PresentCallFPS with UniqueVisualFPS. Actual pixel decoding belongs to the capture gate.\n")
message(STATUS "Encoder LocalDesktop entry evidence: ${pbArtifactDirectory}")
