if(NOT DEFINED PB_ENCODER OR NOT DEFINED PB_EVIDENCE_ROOT)
    message(FATAL_ERROR "PB_ENCODER and PB_EVIDENCE_ROOT are required")
endif()
string(RANDOM LENGTH 24 ALPHABET 0123456789abcdef pbArtifactSuffix)
set(pbArtifactDirectory "${PB_EVIDENCE_ROOT}/encoder-${pbArtifactSuffix}")
if(EXISTS "${pbArtifactDirectory}")
    message(FATAL_ERROR "Encoder test artifact path already exists")
endif()
file(MAKE_DIRECTORY "${pbArtifactDirectory}")
set(pbTelemetry "${pbArtifactDirectory}/呈现-telemetry.jsonl")
execute_process(
    COMMAND "${PB_ENCODER}" --data-window --frames 12 --telemetry "${pbTelemetry}"
    RESULT_VARIABLE pbExit OUTPUT_VARIABLE pbOutput ERROR_VARIABLE pbError TIMEOUT 30)
file(WRITE "${pbArtifactDirectory}/stdout.json" "${pbOutput}")
file(WRITE "${pbArtifactDirectory}/stderr.txt" "${pbError}")
if(NOT pbExit STREQUAL "0")
    message(FATAL_ERROR "Encoder positive integration failed: ${pbExit}\n${pbOutput}\n${pbError}")
endif()
foreach(pbField IN ITEMS submittedFrames totalPresentCalls totalSuccessfulPresents discardedEpochFrames replacedPendingFrames)
    string(JSON ${pbField} GET "${pbOutput}" ${pbField})
endforeach()
if(NOT submittedFrames EQUAL 12 OR totalPresentCalls LESS 1 OR NOT totalPresentCalls EQUAL totalSuccessfulPresents)
    message(FATAL_ERROR "Encoder did not perform its finite data-window submission run: ${pbOutput}")
endif()
math(EXPR pbAccounted "${totalSuccessfulPresents}+${discardedEpochFrames}+${replacedPendingFrames}")
if(NOT pbAccounted EQUAL submittedFrames)
    message(FATAL_ERROR "Encoder submission accounting is incomplete: ${pbOutput}")
endif()
foreach(pbField IN ITEMS candidateContractSatisfied perMonitorV2 latencyWaitable bgraUnorm noMsaa alphaIgnored scalingNone tearingDisabled)
    string(JSON pbValue GET "${pbOutput}" ${pbField})
    if(NOT pbValue)
        message(FATAL_ERROR "Encoder native contract ${pbField} was false: ${pbOutput}")
    endif()
endforeach()
foreach(pbField IN ITEMS pendingFrame inFlightFrame softwareRasterizer)
    string(JSON pbValue GET "${pbOutput}" ${pbField})
    if(pbValue)
        message(FATAL_ERROR "Unexpected Encoder final state ${pbField}: ${pbOutput}")
    endif()
endforeach()
string(JSON pbBufferCount GET "${pbOutput}" bufferCount)
string(JSON pbLatency GET "${pbOutput}" maximumFrameLatency)
string(JSON pbWidth GET "${pbOutput}" DataWindowPhysicalSize 0)
string(JSON pbHeight GET "${pbOutput}" DataWindowPhysicalSize 1)
if(NOT pbBufferCount EQUAL 2 OR NOT pbLatency EQUAL 1 OR NOT pbWidth EQUAL 1920 OR NOT pbHeight EQUAL 1080)
    message(FATAL_ERROR "Encoder default configuration changed: ${pbOutput}")
endif()
string(JSON pbVisualType TYPE "${pbOutput}" PresentedVisualFPS)
if(NOT pbVisualType STREQUAL "NUMBER" AND NOT pbVisualType STREQUAL "NULL")
    message(FATAL_ERROR "Invalid visual metric representation: ${pbOutput}")
endif()
# Deliberately no call-FPS/visual-FPS equality check. DXGI availability and
# observation coverage are evaluated by PBPresentTiming, not guessed here.
file(STRINGS "${pbTelemetry}" pbTelemetryLines ENCODING UTF-8)
foreach(pbLine IN LISTS pbTelemetryLines)
    string(JSON pbSchema GET "${pbLine}" schema_version)
    if(NOT pbSchema EQUAL 1)
        message(FATAL_ERROR "Invalid telemetry schema")
    endif()
endforeach()
list(LENGTH pbTelemetryLines pbLineCount)
if(pbLineCount LESS 1)
    message(FATAL_ERROR "Encoder failed to write Unicode-path telemetry")
endif()
file(SHA256 "${pbTelemetry}" pbBeforeDigest)
execute_process(
    COMMAND "${PB_ENCODER}" --data-window --frames 1 --telemetry "${pbTelemetry}"
    RESULT_VARIABLE pbOverwriteExit OUTPUT_VARIABLE pbOverwriteOutput ERROR_VARIABLE pbOverwriteError TIMEOUT 10)
file(SHA256 "${pbTelemetry}" pbAfterDigest)
if(NOT pbOverwriteExit STREQUAL "1" OR NOT pbBeforeDigest STREQUAL pbAfterDigest)
    message(FATAL_ERROR "Encoder did not reject telemetry overwrite without mutation: ${pbOverwriteExit}\n${pbOverwriteOutput}\n${pbOverwriteError}")
endif()
file(WRITE "${pbArtifactDirectory}/gate.txt"
    "PASS: 12 bounded CPU submissions, actual native Presents, PMv2/default contract, Unicode telemetry, no-overwrite immutability.\nPresentedVisualFPS is not inferred from PresentCallFPS.\n")
message(STATUS "Encoder integration evidence: ${pbArtifactDirectory}")
