function(PbValidateBuildOptions)
    if(PB_BUILD_DESKTOP_LEVELS_GATE AND NOT (WIN32 AND BUILD_TESTING AND PB_BUILD_TESTS AND PB_BUILD_APPS AND PB_BUILD_TOOLS))
        message(FATAL_ERROR
            "PB_BUILD_DESKTOP_LEVELS_GATE requires Windows, BUILD_TESTING=ON, PB_BUILD_TESTS=ON, PB_BUILD_APPS=ON and PB_BUILD_TOOLS=ON")
    endif()
    if(PB_BUILD_LOCAL_DESKTOP_GATE AND NOT (WIN32 AND BUILD_TESTING AND PB_BUILD_TESTS))
        message(FATAL_ERROR
            "PB_BUILD_LOCAL_DESKTOP_GATE requires Windows, BUILD_TESTING=ON and PB_BUILD_TESTS=ON")
    endif()
    if(PB_BUILD_DXGI_GATE AND NOT (WIN32 AND BUILD_TESTING AND PB_BUILD_TESTS))
        message(FATAL_ERROR
            "PB_BUILD_DXGI_GATE requires Windows, BUILD_TESTING=ON and PB_BUILD_TESTS=ON")
    endif()
    if(PB_BUILD_WGC_GATE AND NOT (WIN32 AND BUILD_TESTING AND PB_BUILD_TESTS))
        message(FATAL_ERROR
            "PB_BUILD_WGC_GATE requires Windows, BUILD_TESTING=ON and PB_BUILD_TESTS=ON")
    endif()
    if(PB_BUILD_SCREEN_REGION_GATE AND NOT (WIN32 AND BUILD_TESTING AND PB_BUILD_TESTS))
        message(FATAL_ERROR
            "PB_BUILD_SCREEN_REGION_GATE requires Windows, BUILD_TESTING=ON and PB_BUILD_TESTS=ON")
    endif()
    if(PB_BUILD_PRESENTATION_GATE AND NOT (WIN32 AND BUILD_TESTING AND PB_BUILD_TESTS))
        message(FATAL_ERROR
            "PB_BUILD_PRESENTATION_GATE requires Windows, BUILD_TESTING=ON and PB_BUILD_TESTS=ON")
    endif()
    if(PB_BUILD_FUZZERS AND PB_BUILD_BENCHMARKS)
        message(FATAL_ERROR
            "PB_BUILD_FUZZERS and PB_BUILD_BENCHMARKS are mutually exclusive; configure separate build directories.")
    endif()
endfunction()
